import "dotenv/config";
import { PrismaClient } from "@prisma/client";
import { PrismaBetterSqlite3 } from "@prisma/adapter-better-sqlite3";
import bcrypt from "bcryptjs";
import path from "path";

const dbPath = path.resolve(__dirname, "..", "dev.db");
const adapter = new PrismaBetterSqlite3({ url: `file:${dbPath}` });
const prisma = new PrismaClient({ adapter });

const designInternships = [
  { company: "Riot Games", role: "Internship Programs - Watch for 2027!", category: "Game Companies", paid: true, availability: "soon", url: "https://www.riotgames.com/en/university-programs", deadline: "Applications open September 2026 for Summer 2027", period: "Summer 2027 (12 weeks, remote)", location: "Remote (1 week at LA HQ)", undergradEligible: true, description: "💰 $35-56/hr! 🎮 Summer 2026 roles closed (Jan 9). NEW roles post Sept 2026! Concept Art, Visual Design, 3D Art, Engineering. Remote with LA HQ week!", contact: "Check riotgames.com/university-programs starting Sept 2026", about: "12-week remote internships across Riot. Past roles: Concept Art, Visual Design, 3D Environment Art, Software Engineering. Work on League, VALORANT, TFT, 2XKO. Includes 1 week at LA HQ!", candidate: "Graduating 2027-2028. Strong portfolio required for art/design roles. Passion for Riot games essential.", skills: "Varies by role: Character/environment art, UI/UX design (Figma), 3D modeling, programming.", materials: "Resume, portfolio/demo reel. Applications evaluated rolling basis. Apply early when positions open in September!" },
  { company: "Netflix", role: "Creative Innovation Intern", category: "Media & Entertainment", paid: true, availability: "open", url: "https://explore.jobs.netflix.net/careers/job/790313701820", deadline: "February 6, 2026 - APPLY NOW!", period: "Summer 2026 (12 weeks)", location: "Los Angeles (relocation + housing support provided!)", undergradEligible: true, description: "💰 $40-110/hr! 🎬 URGENT - Closes Feb 6! Work with Content Operations & Innovation. Relocation + housing support!", contact: "Apply through explore.jobs.netflix.net", about: "Support creative and production innovation at Netflix. Research emerging media/production tech, evaluate new tools, create workflows for creative teams.", candidate: "Enrolled in university (bachelor's or master's). Graduating Dec 2026 or Spring 2027. Passion for GenAI and creative tools.", skills: "Research, analysis, communication, workflow design. Interest in emerging technologies and creative tools.", materials: "Resume. Answer essay question about evaluating new tools for Netflix. Applications close Feb 6, 2026!" },
  { company: "Netflix", role: "Summer Internship Programs (General)", category: "Media & Entertainment", paid: true, availability: "check", url: "https://jobs.netflix.com/careers/internships", deadline: "Applications typically open late summer/early fall", period: "Summer 2026 (12 weeks minimum)", location: "Los Gatos or Los Angeles", undergradEligible: true, description: "💰 $40-110/hr! 🎬 Multiple roles: Engineering, Data, Content, Marketing. Postings usually start Aug/Sept!", contact: "Apply through jobs.netflix.com/careers/internships", about: "12-week summer internships across Engineering, Data & Insights, Content, Finance & Strategy, Marketing.", candidate: "Enrolled in bachelor's, master's, or doctoral programs. Passion for entertainment/tech.", skills: "Varies by role - technical for engineering/data, creative for content/marketing.", materials: "Resume, sometimes portfolio or take-home assessment. Check site starting August 2026!" },
  { company: "Roblox", role: "Content Design Intern", category: "Game Companies", paid: true, availability: "open", url: "https://careers.roblox.com/jobs/7612803", deadline: "Rolling applications", period: "Summer 2026 (12 weeks)", location: "San Mateo (hybrid - Tue/Wed/Thu in office)", undergradEligible: true, description: "💰 Competitive pay! 🎮 CURRENTLY OPEN! Craft user experiences for 111M+ daily users.", contact: "Apply through careers.roblox.com", about: "Work within Design and Creative team alongside product managers and engineers.", candidate: "Enrolled in undergrad/grad in English, Communications, HCI, Design, or related field.", skills: "Content design, UX writing, information architecture, design thinking.", materials: "Resume, portfolio. Sign up for Speak_ platform for practice assessments." },
  { company: "Roblox", role: "Software Engineering Intern", category: "Game Companies", paid: true, availability: "open", url: "https://careers.roblox.com/jobs/7114765", deadline: "Rolling applications", period: "Summer 2026 (12 weeks)", location: "San Mateo (hybrid - Tue/Wed/Thu in office)", undergradEligible: true, description: "💰 High pay! 🎮 For CS/tech students. Work on platform serving 111M+ daily users.", contact: "Apply through careers.roblox.com", about: "Join supportive software engineering team. Deliver work to production.", candidate: "Pursuing degree in CS, engineering, or tech-related field.", skills: "Programming, data structures, algorithms, object-oriented programming.", materials: "Resume, portfolio/GitHub. Use Speak_ platform for preparation." },
  { company: "Roblox", role: "Associate Product Designer (21-month program)", category: "Game Companies", paid: true, availability: "open", url: "https://careers.roblox.com/jobs/7167345", deadline: "Rolling applications for 2026 start", period: "21-month rotational program starting 2026", location: "San Mateo (hybrid - Tue/Wed/Thu in office)", undergradEligible: true, description: "💰 Competitive! 🎮 21-MONTH rotational program for new grads! Design for 111M users.", contact: "Apply through careers.roblox.com", about: "21-month rotational program for early career designers. Direct mentorship from industry-leading designers.", candidate: "Possess or will possess undergrad/grad degree in UX/UI, Interaction, Motion, Graphics, Typography, Web, or Product Design.", skills: "UX/UI design, prototyping, user research, competitive analysis. Design systems.", materials: "Resume, portfolio required. Shows: features, prototypes, research process." },
  { company: "Sony Pictures Animation", role: "Marketing Intern", category: "Animation & VFX", paid: true, availability: "soon", url: "https://www.sonypicturesanimation.com/careers/job-postings", deadline: "Applications close February 27, 2026", period: "Summer 2026 (5 weeks, full-time)", location: "Culver City, CA", undergradEligible: true, description: "💰 $19/hr! 🎬 5-week PAID program. Work on campaigns for SPA films! Deadline approaching!", contact: "Apply through Sony Pictures jobs site", about: "Support Marketing team in developing and executing campaigns for Sony Pictures Animation films.", candidate: "Students interested in animation marketing, branding, creative campaigns.", skills: "Campaign planning, research, creative marketing, brand integration.", materials: "Resume, cover letter. Deadline Feb 27, 2026!" },
  { company: "Sony Pictures Animation", role: "Creative Group Intern", category: "Animation & VFX", paid: true, availability: "check", url: "https://www.sonypicturesanimation.com/careers/job-postings", deadline: "Check for Summer 2026 postings (Spring posted Jan-Apr)", period: "Varies by term", location: "Culver City, CA", undergradEligible: true, description: "🎬 Work with executives who develop and oversee animated movies!", contact: "Apply through Sony Pictures careers", about: "Work with creative executives who develop and oversee theatrical animated films.", candidate: "Students in film, animation, entertainment, or related fields.", skills: "Script analysis, research, note-taking, presentation building.", materials: "Resume, cover letter. Check sonypicturesjobs.com regularly." },
  { company: "Sony Pictures Imageworks", role: "Internship Program (iCAD)", category: "Animation & VFX", paid: true, availability: "check", url: "https://www.imageworks.com/icad/internships", deadline: "Check website for application periods", period: "Summer (paid internship)", location: "Vancouver, Canada", undergradEligible: true, description: "🎬 World-class VFX studio! Must be eligible to work in Canada.", contact: "Apply through Imageworks careers", about: "Get paid to learn from industry leaders. Work on live action or CG animated feature films.", candidate: "Recent graduates and current students. Must be eligible to work in Canada.", skills: "Computer animation, digital arts, computer science.", materials: "Resume, demo reel/portfolio. Review 'Reel Advice' on website." },
  { company: "Pixar Animation Studios", role: "Art Department Intern", category: "Animation & VFX", paid: true, availability: "check", url: "https://www.disneycareers.com/en/job/emeryville/art-department-intern-summer-2026/391/89182146960", deadline: "Check Disney Careers for deadlines (typically winter/spring)", period: "Summer 2026 (12 weeks)", location: "Emeryville, CA (Bay Area!)", undergradEligible: true, description: "💰 $22.50/hr! 🎬 DREAM OPPORTUNITY at Pixar! Character Design, Set Design, Color/Shading, or Graphic Design tracks.", contact: "Apply through Disney Careers", about: "Work with mentors and Art Department gaining feature film experience.", candidate: "Interest in visual storytelling. Strengths in illustration, drawing, painting, animation.", skills: "Choose ONE focus: Character Design, Set Design, Color/Shading/Lighting Design, or Graphic Design.", materials: "Single PDF: resume + cover letter. Portfolio/demo reel link required." },
  { company: "Pixar Animation Studios", role: "Product Design Intern", category: "Animation & VFX", paid: true, availability: "check", url: "https://www.disneycareers.com/en/job/emeryville/product-design-intern-summer-2026/391/89182147008", deadline: "Check Disney Careers (typically posted late fall-spring)", period: "Summer 2026 (12 weeks)", location: "Emeryville, CA (Bay Area!)", undergradEligible: true, description: "💰 $41.40/hr! 🎬 INCREDIBLE PAY! UX/UI/product design for film tech.", contact: "Apply through Disney Careers", about: "Contribute to product innovation. Work on products used in Pixar's filmmaking process.", candidate: "Pursuing degree in design, HCI, or related field.", skills: "Product design, UX/UI, prototyping, user research.", materials: "Resume, portfolio. Check pixar.com/careers regularly." },
  { company: "Walt Disney Animation Studios", role: "Internship & Apprenticeship Programs", category: "Animation & VFX", paid: true, availability: "check", url: "https://disneyanimation.com/interns-apprentices/", deadline: "Internships posted late fall-spring; Apprenticeships year-round", period: "10-12 weeks (internships)", location: "Burbank, CA", undergradEligible: true, description: "🎬 Legacy Disney animation! Craft-based mentorship from Disney artists/engineers.", contact: "Apply through Disney Animation careers", about: "Mentored opportunities across production, technology, and studio teams.", candidate: "Students and recent graduates. Passion for animation storytelling.", skills: "Varies by role - production, art, animation, technology.", materials: "Portfolio essential - showcase versatility and originality." },
  { company: "Disney", role: "Graphic Design Intern (D+/Disney Bundle)", category: "Media & Entertainment", paid: true, availability: "check", url: "https://www.disneycareers.com/en/job/burbank/d-graphic-design-intern-summer-2026/391/90960654096", deadline: "Check Disney Careers for deadline", period: "Summer 2026 (June-August)", location: "Burbank, CA", undergradEligible: true, description: "💰 $22.50/hr! 🎬 Design for Disney+ and Disney Bundle!", contact: "Apply through Disney Careers", about: "Create designs for Disney+ and Disney Bundle following brand style guides.", candidate: "Majoring in graphic design, digital design, entertainment design.", skills: "Adobe Creative Suite, Google Suite, Microsoft Office.", materials: "Portfolio required (website or PDF)." },
  { company: "Disney Consumer Products", role: "Character Art Intern", category: "Design Studios", paid: true, availability: "check", url: "https://www.disneycareers.com/en/internships-united-states", deadline: "Check Disney Careers", period: "Summer/Fall 2026 (3-6 months)", location: "Glendale, CA", undergradEligible: true, description: "🎨 Design Disney characters for consumer products!", contact: "Apply through Disney Careers", about: "Create character art for Disney Consumer Products.", candidate: "Art/design students passionate about Disney characters.", skills: "Character design, illustration, digital art.", materials: "Portfolio required. Resume." },
  { company: "Blizzard Entertainment", role: "Check for Summer Internships", category: "Game Companies", paid: true, availability: "check", url: "https://careers.blizzard.com/", deadline: "Varies - check careers site", period: "Summer 2026", location: "Irvine, CA", undergradEligible: true, description: "🎮 Creators of Overwatch, World of Warcraft, Diablo!", contact: "Apply through Blizzard careers", about: "Leading game company known for Overwatch, WoW, Diablo.", candidate: "Game design, art, animation students.", skills: "Varies by role - concept art, 3D modeling, animation, UI/UX.", materials: "Resume, portfolio/demo reel." },
  { company: "Electronic Arts (EA)", role: "Design/Art Internships", category: "Game Companies", paid: true, availability: "check", url: "https://www.ea.com/careers/interns-and-university-graduates", deadline: "Typically open fall/winter for summer", period: "Summer 2026 (12 weeks)", location: "Various (LA, Bay Area, etc.)", undergradEligible: true, description: "🎮 Major game publisher! FIFA, Apex Legends, The Sims, etc.", contact: "Apply through EA careers", about: "Work on major franchises like FIFA, Madden, Apex Legends, The Sims.", candidate: "Game design/art students. Portfolio required.", skills: "Varies - concept art, 3D art, animation, UI/UX.", materials: "Resume, portfolio. Applications typically open late fall." },
  { company: "BUCK (Design Studio)", role: "Check for Internship Programs", category: "Design Studios", paid: false, availability: "check", url: "https://buck.co/careers", deadline: "Varies", period: "Varies", location: "Los Angeles, NY", undergradEligible: true, description: "🎨 Prestigious design/animation studio! Motion graphics, 3D animation.", contact: "careers@buck.co", about: "Leading creative studio specializing in design, animation, motion graphics.", candidate: "Motion design, animation, graphic design students.", skills: "Motion graphics, 3D animation, After Effects, Cinema 4D.", materials: "Check buck.co/careers for current openings." },
  { company: "Method Studios / Framestore", role: "VFX Internships", category: "Animation & VFX", paid: false, availability: "check", url: "https://www.methodstudios.com/careers", deadline: "Check careers sites", period: "Varies", location: "Los Angeles, Vancouver", undergradEligible: true, description: "🎬 Major VFX studios! Work on blockbuster films and TV shows.", contact: "Apply through respective careers sites", about: "VFX and animation for major films and TV.", candidate: "VFX, animation, or related students.", skills: "VFX, compositing, 3D modeling, animation. Maya, Nuke, Houdini.", materials: "Demo reel, resume." },
  { company: "DreamWorks Animation", role: "Check for Internship Programs", category: "Animation & VFX", paid: true, availability: "check", url: "https://www.dreamworks.com/jobs", deadline: "Check careers site", period: "Summer typically", location: "Glendale, CA", undergradEligible: true, description: "🎬 How to Train Your Dragon, Kung Fu Panda, Shrek!", contact: "Apply through DreamWorks careers", about: "Major animation studio creating beloved films.", candidate: "Animation, art, or related students.", skills: "Varies - animation, character/environment art, rigging, lighting.", materials: "Portfolio/demo reel required." },
  { company: "Sephora", role: "Visual Design Intern", category: "Creative Agencies", paid: true, availability: "open", url: "https://join.sephora.com/careers/job/790299319018", deadline: "Rolling applications", period: "Summer 2026 (10 weeks: June 1 - August 14)", location: "Remote (CA) + 1 week in San Francisco HQ", undergradEligible: true, description: "💰 $25/hr! 💄 CURRENTLY OPEN! Remote + paid SF week! Create graphics for eLearning, mobile/desktop.", contact: "Apply through join.sephora.com", about: "Support Retail Engagement team. Create compelling graphics and interactive elements.", candidate: "Pursuing degree in Graphic Design, Visual Design, or related field.", skills: "Adobe Creative Suite (Illustrator, Photoshop, InDesign), visual design.", materials: "Resume, portfolio showcasing visual design work." },
  { company: "Sephora", role: "Summer Internship Program (Multiple Roles)", category: "Creative Agencies", paid: true, availability: "open", url: "https://www.inside-sephora.com/en/usa/sephora-internships", deadline: "Rolling - applications opened October 2025", period: "Summer 2026 (10 weeks)", location: "Remote (CA) + 1 week in San Francisco", undergradEligible: true, description: "💰 $25/hr! 💄 Multiple roles: Marketing, Merchandising, Finance, Engineering.", contact: "Apply through inside-sephora.com or join.sephora.com", about: "10-week paid corporate internship program. Work on impactful projects.", candidate: "Graduating 2026 or 2027. All majors welcome.", skills: "Varies by role - design, marketing, merchandising, engineering.", materials: "Resume. Check inside-sephora.com for specific roles." },
  { company: "Vercel", role: "Engineering Summer Intern", category: "Tech/Product Design", paid: true, availability: "open", url: "https://vercel.com/careers/engineering-summer-intern-5628292004", deadline: "Rolling applications", period: "Summer 2026 (12 weeks typical)", location: "Remote - work across time zones", undergradEligible: true, description: "💰 $9,500-$11,000/month! 🚀 Work on Next.js, v0, AI SDK! Design engineering opportunities!", contact: "Apply through vercel.com/careers", about: "Work on REAL production projects at Vercel - creators of Next.js, v0 (AI design tool), and AI SDK.", candidate: "Pursuing degree in Computer Science, Engineering, or related field.", skills: "JavaScript, TypeScript. Next.js, React. 'Design engineering' mindset.", materials: "Resume. Perfect for DMA students who code!" },
  { company: "Warner Bros. Discovery", role: "Design Internships (Multiple Locations)", category: "Media & Entertainment", paid: true, availability: "closed", url: "https://careers.wbd.com/global/en/c/early-careers-jobs", deadline: "February 22, 2026 - PASSED", period: "Summer 2026 (11 weeks)", location: "LA, NYC, Atlanta, Burbank (hybrid)", undergradEligible: true, description: "⚠️ DEADLINE PASSED (Feb 22)! Next year: Apply early Fall 2026 for Summer 2027.", contact: "careers.wbd.com", about: "Award-winning global internship program. HBO, CNN, Max, Bleacher Report, TLC, Food Network.", candidate: "Rising Junior, Senior, or Graduate Student. 3.0+ GPA required.", skills: "Adobe Creative Suite, Figma. Strong design and typography skills.", materials: "Resume + portfolio. For 2027: Set alert on careers.wbd.com in September 2026!" },
  { company: "Warner Bros. Discovery", role: "WB Animation - Creative Services (Graphic Design)", category: "Animation & VFX", paid: true, availability: "closed", url: "https://careers.wbd.com/global/en/c/early-careers-jobs", deadline: "February 22, 2026 - PASSED", period: "Summer 2026 (11 weeks)", location: "Burbank, CA (hybrid)", undergradEligible: true, description: "⚠️ DEADLINE PASSED! Next summer: Apply Fall 2026.", contact: "careers.wbd.com", about: "Warner Bros. Animation Creative Services team.", candidate: "Rising Junior, Senior, or Grad Student. 3.0+ GPA.", skills: "Adobe Creative Suite. Typography skills. Brand design.", materials: "Resume + graphic design portfolio." },
  { company: "Fuser", role: "Brand & Motion Design Intern", category: "Creative Agencies", paid: true, availability: "open", url: "https://fuser.studio/careers", deadline: "Rolling applications", period: "6 months (potential for full-time conversion)", location: "Hybrid - Los Angeles (1 day/week in office)", undergradEligible: true, description: "💰 $37k-$42k (6 months)! 🎬 CURRENTLY OPEN! AI creative tool company!", contact: "Apply through fuser.studio/careers", about: "Creative technology company building AI-powered collaborative canvas.", candidate: "Emerging designers who think in movement and systems.", skills: "Figma, Photoshop, + at least one motion tool (After Effects, Cavalry, Rive).", materials: "Portfolio with process work. Potential to convert to full-time!" },
  { company: "Figma", role: "Product Design Intern", category: "Tech/Product Design", paid: true, availability: "open", url: "https://job-boards.greenhouse.io/figma/jobs/5616453004", deadline: "Applications typically open fall for following summer", period: "Summer 2026 (dates TBD)", location: "San Francisco or New York (in-person required)", undergradEligible: true, description: "🎨 CURRENTLY OPEN! Own impactful projects from ideation to execution! Housing stipend + travel reimbursement.", contact: "Apply through job-boards.greenhouse.io/figma", about: "OWN real impactful projects from start to finish at Figma!", candidate: "Demonstrated baseline in visual design and/or interaction design.", skills: "Visual design, interaction design, prototyping, product strategy.", materials: "Portfolio showcasing design excellence and creative process." },
  { company: "Hasbro", role: "Graphic Design Intern - Games", category: "Design Studios", paid: true, availability: "open", url: "https://jobs.hasbro.com/content/student-programs/?locale=en_US", deadline: "Interview Timeline: February - April 2026", period: "11 weeks (June 8 - August 21, 2026)", location: "Pawtucket, RI (in-person required)", undergradEligible: true, description: "💰 $27/hr! 🎲 CURRENTLY OPEN! Design board games! Monopoly, Nerf, Transformers!", contact: "Apply through jobs.hasbro.com", about: "Work with Hasbro's Games creative team on game components, box design, rules layout.", candidate: "Currently enrolled in Graphic Design, Fine Arts, or related degree.", skills: "HIGHLY proficient in: Illustrator, Photoshop, Acrobat, InDesign.", materials: "Portfolio showing graphic design work. Resume." },
  { company: "Mattel / Fisher-Price", role: "Summer Internship Program - Check for Design Roles", category: "Design Studios", paid: true, availability: "check", url: "https://jobs.mattel.com/en/category/internship-jobs/2015/61215/1", deadline: "Applications typically open late fall/early winter", period: "10-12 weeks Summer 2026", location: "El Segundo, CA (HQ) - some hybrid options", undergradEligible: true, description: "🧸 Design toys for iconic brands! Barbie, Hot Wheels, Fisher-Price!", contact: "Apply through jobs.mattel.com", about: "Mattel's internship program for future leaders! Barbie, Hot Wheels, Fisher-Price, American Girl.", candidate: "Enrolled undergraduate/graduate students. Passion for toys and entertainment.", skills: "Adobe Photoshop, Illustrator. 3D modeling software is a plus.", materials: "Resume + cover letter. Portfolio required for design roles." },
  { company: "TikTok", role: "Product Designer Intern (TikTok-Design-UX)", category: "Tech/Product Design", paid: true, availability: "open", url: "https://lifeattiktok.com/search/7533145462880127240", deadline: "Rolling applications - apply early!", period: "12 weeks Summer 2026", location: "San Jose, CA", undergradEligible: true, description: "💰 $30/hr + housing allowance! 📱 CURRENTLY OPEN! Design for global short-video platform!", contact: "Apply through lifeattiktok.com - Max 2 positions", about: "Design for TikTok's creative short video platform targeting global users.", candidate: "Pursuing undergraduate or graduate degree. MUST submit portfolio.", skills: "Interaction design, Figma prototyping.", materials: "Resume with CLEAR availability. PORTFOLIO REQUIRED." },
  { company: "Hasbro", role: "Graphic Design Intern (Games)", category: "Game Companies", paid: true, availability: "open", url: "https://jobs.hasbro.com/go/Internships-&-Co-ops/8206000/", deadline: "Rolling applications", period: "11 weeks (June 8 - August 21, 2026)", location: "Pawtucket, RI (in-person required)", undergradEligible: true, description: "💰 $24-27/hr! 🎲 CURRENTLY OPEN! Work on Games creative projects.", contact: "Apply through jobs.hasbro.com", about: "11-week paid internship working on Games creative projects.", candidate: "Enrolled in Graphic Design, Fine Arts, or related.", skills: "Illustrator, Photoshop, Acrobat, InDesign.", materials: "Resume. Portfolio recommended." },
  { company: "Hasbro", role: "Product Design Co-op (Action Brands)", category: "Game Companies", paid: true, availability: "open", url: "https://jobs.hasbro.com/go/Internships-&-Co-ops/8206000/", deadline: "Rolling applications", period: "Summer/Fall 2026", location: "Pawtucket, RI (in-person)", undergradEligible: true, description: "💰 $29-33/hr! 🎮 CURRENTLY OPEN! Design TOYS for Star Wars, Transformers, G.I. Joe!", contact: "Apply through jobs.hasbro.com", about: "Hasbro Action Brands team. Ideating play experiences, visualizing toy concepts, prototyping.", candidate: "Creative students passionate about toys and action figures.", skills: "Product design/development. Creative problem solving.", materials: "Resume + portfolio." },
  { company: "Notion", role: "Software Engineer Intern (Design Engineering)", category: "Tech/Product Design", paid: true, availability: "open", url: "https://jobs.ashbyhq.com/notion/23ac2477-0008-4bed-b1c1-81f90a32e9e6", deadline: "Rolling applications", period: "12 weeks (May - September 2026)", location: "San Francisco or New York (in-person required)", undergradEligible: true, description: "💻 CURRENTLY OPEN! Design-first company! Ship real features to millions!", contact: "Apply through jobs.ashbyhq.com/notion", about: "Work on real projects that ship to production! Design-first philosophy.", candidate: "Pursuing Bachelor's/Master's in CS, Engineering, or related.", skills: "TypeScript, Node.js, Go, Python. CSS, JavaScript, React.", materials: "Resume. MUST be able to work in-person." },
  { company: "Notion", role: "UX Research Intern", category: "Tech/Product Design", paid: true, availability: "open", url: "https://jobs.ashbyhq.com/notion/2e7b83cd-9210-4492-ad30-7b898b80807b", deadline: "Rolling applications", period: "Full-time (May - September 2026)", location: "San Francisco (in-person required)", undergradEligible: false, description: "🔬 Research how users discover/adopt Calendar, Mail, AI! Graduate students only.", contact: "Apply through jobs.ashbyhq.com/notion", about: "Research user discovery and adoption of Notion's expanding ecosystem.", candidate: "Master's or PhD in HCI, Psychology, Cognitive Science.", skills: "Research methods (qualitative/quantitative). Product sense.", materials: "Resume showing research experience." },
];

const polisciInternships = [
  { company: "SF City Attorney's Office", role: "Summer Internship Program", category: "Legal & Law", paid: false, availability: "open", url: "https://sfcityattorney.org/aboutus/internships/", deadline: "Rolling — accepting until filled", period: "Summer 2026 (10 weeks, full-time)", location: "San Francisco", undergradEligible: false, description: "⚠️ LAW STUDENTS ONLY. Rolling admissions, still open! Pick 3 preferred practice teams.", contact: "Allie.Saperstein@sfcityatty.org", about: "Nationally ABA-recognized municipal law office. Work across 100+ city departments on real legal matters.", candidate: "Law students only (summer full-time). Seeking future leaders in government and public-interest law.", skills: "Legal research, writing, interest in municipal government & public interest law.", materials: "Cover letter, resume, brief legal writing sample." },
  { company: "City of San José", role: "Student Intern Program", category: "Government & Policy", paid: true, availability: "open", url: "https://www.sanjoseca.gov/your-government/departments-offices/human-resources/browse-city-jobs/student-opportunities", deadline: "Ongoing — ~150 interns hired annually", period: "Flexible year-round (works around class schedule)", location: "San José", undergradEligible: true, description: "💰 PAID! ✅ UNDERGRAD OK. One of the best options — flexible hours, many departments.", contact: "City of San José HR — see jobs portal", about: "Professional public sector work across city departments including urban planning, public admin, finance, and policy.", candidate: "Must be currently enrolled in college. Political science, public administration, and many other majors accepted.", skills: "Communication, analytical thinking, organizational skills.", materials: "Apply through City of San José jobs portal online." },
  { company: "CA Attorney General's Office", role: "Student Intern / Volunteer", category: "Government & Policy", paid: false, availability: "open", url: "https://oag.ca.gov/careers/students", deadline: "Currently accepting — multiple positions listed", period: "Varies by position (summer and ongoing)", location: "San Francisco / Sacramento", undergradEligible: true, description: "✅ UNDERGRAD OK. State-level DOJ experience. Multiple divisions.", contact: "See individual listings at oag.ca.gov/careers/students", about: "Work within the CA Department of Justice. Divisions include public safety, civil rights, consumer protection.", candidate: "Currently enrolled students including undergraduates.", skills: "Research, analytical writing, attention to detail.", materials: "State Application (STD 678) plus materials specified per listing." },
  { company: "Bay Area Council", role: "Summer Associates Program", category: "Government & Policy", paid: false, availability: "soon", url: "https://www.bayareacouncil.org/internship-program/", deadline: "Applications open March/April 2026", period: "Summer 2026 (immersive program)", location: "San Francisco", undergradEligible: true, description: "✅ UNDERGRAD OK (juniors/seniors). Applications opening very soon!", contact: "Check website when applications open", about: "Immersive experience in policy research & analysis, program design, global trade, event management.", candidate: "Collegiate juniors, seniors, and grad students.", skills: "Policy research, analytical writing, communication, event planning.", materials: "Check website starting March 2026 for application requirements." },
  { company: "Santa Clara County Superior Court", role: "Judicial Summer Internship", category: "Legal & Law", paid: false, availability: "open", url: "https://santaclara.courts.ca.gov/general-information/employment/interns-volunteers", deadline: "Check court Employment page", period: "Summer 2026 (June–July, 2 months)", location: "San José", undergradEligible: true, description: "✅ UNDERGRAD OK. Structured program under Judicial Officers.", contact: "internship@scscourt.org", about: "Work under supervision of Judicial Officers in a structured 2-month program.", candidate: "College students (including undergraduates) and graduates.", skills: "Interest in judicial system, attention to detail, professional demeanor.", materials: "Check employment page or email internship@scscourt.org." },
  { company: "Santa Clara Univ. (Resource List)", role: "Bay Area Political Internship Directory", category: "Government & Policy", paid: false, availability: "open", url: "https://www.scu.edu/cas/political-science/beyond-the-classroom/internships-and-fellowships/internships/", deadline: "N/A — use to cold-email orgs directly", period: "Varies by organization", location: "Bay Area wide", undergradEligible: true, description: "🔑 KEY RESOURCE for cold outreach. Lists congressional offices, DA offices, nonprofits, and more.", contact: "Prof. Matt Harrigan — mharrigan@scu.edu", about: "Curated directory listing dozens of Bay Area orgs that take political science interns.", candidate: "Undergrad political science students.", skills: "Varies by org. Generally: research, writing, communication.", materials: "Contact organizations directly with resume and cover letter." },
  { company: "SF District Attorney's Office", role: "Summer College Internship", category: "Legal & Law", paid: false, availability: "check", url: "https://sfdistrictattorney.org/home/careers/college-internships/", deadline: "Summer session not yet posted — email to ask", period: "Summer 2026 (likely June–Aug, TBD)", location: "San Francisco", undergradEligible: true, description: "✅ UNDERGRAD OK. EMAIL them to ask: SFDAInternship@sfgov.org", contact: "SFDAInternship@sfgov.org", about: "Assist prosecutors with case files, trial prep, contacting witnesses, managing subpoenas.", candidate: "Students or recent grads in criminal justice, political science, pre-law.", skills: "Writing, organization, reliability. Writing sample (≤10 pages) required.", materials: "Cover letter, resume, writing sample, gov photo ID, transcript." },
  { company: "SF Dept. of Police Accountability", role: "Fall 2026 Internship", category: "Government & Policy", paid: false, availability: "soon", url: "https://www.sf.gov/apply-internship-dpas-law-and-justice-reform-internship-program", deadline: "Summer 2026 deadline passed. Watch for Fall 2026 cycle.", period: "Fall 2026 (TBD — typically ~4 months)", location: "San Francisco", undergradEligible: true, description: "✅ UNDERGRAD OK. Great justice reform experience.", contact: "dpa.recruitment@sfgov.org", about: "Assist DPA attorneys in trial prep, sentencing, appeals. Police oversight.", candidate: "Students interested in law, justice reform, police accountability.", skills: "Research, writing, interest in criminal justice reform.", materials: "Resume/CV, cover letter, DPA application form." },
  { company: "UC Berkeley Public Service Center", role: "Public Service Internship (PSI)", category: "Nonprofits & Advocacy", paid: false, availability: "soon", url: "https://publicservice.berkeley.edu/programs/public-service-internship/", deadline: "Watch for 2026-27 applications (~spring)", period: "Academic Year 2026-27 (8-10 hrs/week)", location: "Bay Area (various community partners)", undergradEligible: true, description: "✅ UNDERGRAD OK. Cohort model with leadership development.", contact: "UC Berkeley Public Service Center", about: "Year-long cohort program connecting students with Bay Area social justice orgs.", candidate: "UC Berkeley students (primarily), including undergraduates.", skills: "Leadership, community engagement, policy analysis, organizing.", materials: "Application through Public Service Center." },
  { company: "Congressional District Offices", role: "Intern (various representatives)", category: "Government & Policy", paid: false, availability: "open", url: "https://www.scu.edu/cas/political-science/beyond-the-classroom/internships-and-fellowships/internships/", deadline: "Rolling — most accept applications year-round", period: "Summer 2026 or Fall 2026 (flexible)", location: "Bay Area district offices", undergradEligible: true, description: "✅ UNDERGRAD OK. Bay Area reps: Ro Khanna, Nancy Pelosi, Eric Swalwell, Lateefah Simon, Kevin Mullin, Zoe Lofgren, Jimmy Panetta.", contact: "Find contact info on each rep's official website", about: "Work in a congressional district office handling constituent services, policy research, event support.", candidate: "College students, especially political science majors.", skills: "Communication, writing, research, professionalism.", materials: "Resume, cover letter addressed to the specific office." },
  { company: "Rep. Sam Liccardo (CA-16)", role: "Congressional Internship", category: "Government & Policy", paid: false, availability: "check", url: "https://liccardo.house.gov/services/internships", deadline: "Check back — Summer 2026 info not yet posted", period: "Summer 2026 (TBD)", location: "Palo Alto District Office / Washington DC", undergradEligible: true, description: "✅ UNDERGRAD OK. NEW congressman, former San Jose Mayor. Palo Alto is in his district!", contact: "See website when Summer 2026 applications open", about: "Work with Silicon Valley's newest congressman. Focus on housing, public safety, innovation, climate.", candidate: "College students. District residents likely prioritized.", skills: "Constituent services, policy research, communication.", materials: "TBD — check website starting March 2026" },
  { company: "Rep. Ro Khanna (CA-17)", role: "Congressional Internship (PAID)", category: "Government & Policy", paid: true, availability: "open", url: "https://khanna.house.gov/services/internships", deadline: "Applications open for Summer 2026", period: "Summer 2026 (flexible)", location: "Santa Clara District Office / Washington DC", undergradEligible: true, description: "✅ UNDERGRAD OK. 💰 PAID $17.75/hr in DC! District office: $15/hr, 12 hrs/week.", contact: "DC: Khanna.Interns@mail.house.gov | District: Khanna.Districtintern@mail.house.gov", about: "Work on tech policy, housing, innovation with a leading progressive voice.", candidate: "College students or recent grads. District ties (CA-17) prioritized.", skills: "Research, writing, constituent services, professionalism.", materials: "Resume, short writing sample (max 4 pages), availability, reference." },
  { company: "Rep. Kevin Mullin (CA-15)", role: "Congressional Internship", category: "Government & Policy", paid: true, availability: "check", url: "https://kevinmullin.house.gov/services/internships/", deadline: "Currently closed — watch for Summer 2026", period: "Summer 2026 (~4 months, 3 days/week)", location: "San Mateo District Office / Washington DC", undergradEligible: true, description: "✅ UNDERGRAD OK. DC office offers PAID stipend.", contact: "Check website when applications reopen", about: "Serves San Mateo County. Focus on housing, climate, transportation.", candidate: "College students. Flexible schedule to accommodate classes.", skills: "Constituent services, research, communication.", materials: "TBD when applications reopen" },
  { company: "Assemblymember Marc Berman (AD-23)", role: "District Office Internship", category: "Government & Policy", paid: false, availability: "check", url: "https://a23.asmdc.org/district-office-internships", deadline: "Spring deadline passed. Watch for summer.", period: "Varies by term", location: "Palo Alto (721 Colorado Ave, Suite 101)", undergradEligible: true, description: "✅ UNDERGRAD OK. LOCAL! Palo Alto district office. Must reside in AD-23.", contact: "Ruby.Mayne@asm.ca.gov | (650) 324-0224", about: "State Assembly work on California policy. Constituent services, policy research.", candidate: "Must reside in 23rd Assembly District (includes Palo Alto).", skills: "Research, writing, constituent engagement.", materials: "Cover letter, resume, writing sample." },
  { company: "Eric Swalwell for Governor Campaign", role: "Campaign Volunteer/Intern", category: "Campaign & Political Orgs", paid: false, availability: "open", url: "https://www.ericswalwell.com/", deadline: "Primary: June 2, 2026", period: "Through June 2026 primary (ongoing)", location: "East Bay / Statewide", undergradEligible: true, description: "✅ UNDERGRAD OK. GUBERNATORIAL CAMPAIGN! Polling at 14% (tied for 2nd).", contact: "Campaign website contact form", about: "Experience statewide gubernatorial campaign. Phone banking, canvassing, event organizing.", candidate: "Students interested in electoral politics, campaigns, organizing.", skills: "Organizing, communication, phone banking, canvassing.", materials: "Contact through campaign website volunteer form" },
  { company: "Antonio Villaraigosa for Governor Campaign", role: "Campaign Volunteer/Intern", category: "Campaign & Political Orgs", paid: false, availability: "check", url: "https://www.antonioforgovernor.com/", deadline: "Primary: June 2, 2026", period: "Through June 2026 primary", location: "Statewide", undergradEligible: true, description: "✅ UNDERGRAD OK. Former LA Mayor, former Assembly Speaker.", contact: "Campaign website", about: "Work with experienced political operation. Former LA Mayor.", candidate: "Students interested in campaigns and centrist Democratic politics.", skills: "Organizing, outreach, data, communication.", materials: "Contact through campaign website" },
  { company: "Matt Mahan for Governor Campaign", role: "Campaign Volunteer/Intern", category: "Campaign & Political Orgs", paid: false, availability: "open", url: "https://mattmahan.com/", deadline: "Primary: June 2, 2026", period: "Through June 2026 primary", location: "San José / Bay Area", undergradEligible: true, description: "✅ UNDERGRAD OK. Current San Jose Mayor. Silicon Valley moderate. LOCAL!", contact: "Campaign website", about: "Newest gubernatorial campaign. Tech-savvy moderate Democrat.", candidate: "Students interested in moderate Democratic politics, tech policy.", skills: "Tech-savvy organizing, digital outreach, data.", materials: "Contact through campaign website" },
  { company: "Stanford Political Science Dept", role: "Summer Research College (SRC)", category: "Research & Think Tanks", paid: true, availability: "open", url: "https://politicalscience.stanford.edu/undergraduate-program/summer-research-college", deadline: "Rolling basis, no later than Friday, Feb 13, 2026 at 5pm", period: "June 22 - August 28, 2026 (10 weeks)", location: "Stanford Campus", undergradEligible: true, description: "✅ UNDERGRAD OK. 💰 PAID $8,500 stipend! On-campus research with Stanford faculty.", contact: "Margaux Leivenberg (see website)", about: "10-week paid research assistantship working directly with Stanford Political Science faculty.", candidate: "Stanford undergrads only. Must be available 40 hrs/week.", skills: "Research skills, interest in academic research.", materials: "Cover letter for each project, resume, unofficial transcript." },
  { company: "Stanford Public Policy Program", role: "Policy Internships & Fellowships", category: "Research & Think Tanks", paid: false, availability: "check", url: "https://publicpolicy.stanford.edu/beyond-classroom/internships-career-resources", deadline: "Varies by opportunity", period: "Summer 2026 / Academic Year", location: "Various (DC, Bay Area, international)", undergradEligible: true, description: "✅ UNDERGRAD OK (must be declared major). Multiple programs.", contact: "Public Policy Program advising", about: "Various internship/fellowship opportunities for public policy students.", candidate: "Declared public policy or economics majors.", skills: "Policy analysis, research, writing.", materials: "Varies by program — see website." },
  { company: "Stanford Freeman Spogli Institute", role: "Global Policy Internships", category: "Research & Think Tanks", paid: true, availability: "check", url: "https://solo.stanford.edu/", deadline: "Varies by program", period: "Summer 2026", location: "International / Bay Area", undergradEligible: true, description: "✅ UNDERGRAD OK. Up to $9,000 research funding!", contact: "FSI advising", about: "International policy internships and research funding.", candidate: "Stanford students interested in international policy.", skills: "Policy research, international affairs, languages.", materials: "See FSI website and SOLO portal" },
  { company: "San Jose Mayor Matt Mahan", role: "Mayor's Office Internship", category: "Government & Policy", paid: false, availability: "check", url: "https://www.sjmayormatt.com/internships", deadline: "Check website for current cycle", period: "Varies by term", location: "San José", undergradEligible: true, description: "✅ UNDERGRAD OK. LOCAL! Work directly with San Jose Mayor.", contact: "See website for application details", about: "Work directly in the Mayor's Office on issues affecting Silicon Valley's largest city.", candidate: "Undergraduate students interested in local government.", skills: "Policy research, constituent services, project management.", materials: "Check website for current application requirements" },
  { company: "Santa Clara County District Attorney", role: "College Internship Program", category: "Legal & Law", paid: false, availability: "check", url: "https://countyda.sccgov.org/college-internship-program", deadline: "Check website — typically rolling", period: "Varies by term", location: "San José", undergradEligible: true, description: "✅ UNDERGRAD OK. County-level prosecution experience.", contact: "See website for application process", about: "Assist prosecutors with criminal cases, legal research, trial preparation.", candidate: "Undergraduate students interested in criminal justice, pre-law.", skills: "Legal research, writing, attention to detail.", materials: "Application form, resume, cover letter. Background check required." },
  { company: "Santa Clara County Public Defender", role: "Volunteer/Internship Program", category: "Legal & Law", paid: false, availability: "open", url: "https://pdo.santaclaracounty.gov/working-public-defenders-office/volunteer-and-job-opportunities", deadline: "Rolling applications accepted", period: "Flexible", location: "San José", undergradEligible: true, description: "✅ UNDERGRAD OK. Public defense perspective.", contact: "See website for volunteer coordinator contact", about: "Work with public defenders representing clients who cannot afford private attorneys.", candidate: "Undergraduate students interested in criminal justice, civil rights.", skills: "Research, client interaction, legal writing.", materials: "See website for current volunteer application process" },
  { company: "Silicon Valley Leadership Group", role: "Internship Program", category: "Government & Policy", paid: false, availability: "check", url: "https://svlg.org/about-us/internships/", deadline: "Check website for current openings", period: "Varies", location: "San José", undergradEligible: true, description: "✅ UNDERGRAD OK. Business + policy intersection.", contact: "See website for application", about: "Regional business organization working on policy affecting Silicon Valley.", candidate: "Students interested in business-government relations.", skills: "Policy research, business communication, event coordination.", materials: "Resume and cover letter — see website for details" },
  { company: "Senator Josh Becker (SD-13)", role: "State Senate Internship", category: "Government & Policy", paid: false, availability: "check", url: "https://sd13.senate.ca.gov/", deadline: "Check website for current term", period: "Varies by session", location: "Menlo Park / Sacramento", undergradEligible: true, description: "✅ UNDERGRAD OK. VERY LOCAL — Menlo Park office!", contact: "Contact district office", about: "Work with State Senator representing San Mateo County.", candidate: "Students interested in state government, environmental issues.", skills: "Legislative research, constituent services, policy analysis.", materials: "Contact office for internship application process" },
  { company: "Assemblymember Diane Papen (AD-21)", role: "District Office Internship", category: "Government & Policy", paid: false, availability: "check", url: "https://a21.asmdc.org/internship-program", deadline: "Check website for term deadlines", period: "Varies by term", location: "San Mateo", undergradEligible: true, description: "✅ UNDERGRAD OK. Nearby — San Mateo County Assembly district. State-level policy work close to home.", contact: "See website for application", about: "California State Assembly work on San Mateo County issues. Constituent services, policy research, community engagement.", candidate: "Students interested in state government, California policy. Interest in Peninsula issues.", skills: "Research, writing, constituent engagement. Communication and organizational skills.", materials: "See website for current application requirements" },
  { company: "Representative Jimmy Panetta (CA-19)", role: "Congressional Internship", category: "Government & Policy", paid: false, availability: "check", url: "https://panetta.house.gov/services/internships", deadline: "Check website for term deadlines", period: "Summer/Fall/Spring terms", location: "Santa Cruz / Salinas / Washington DC", undergradEligible: true, description: "✅ UNDERGRAD OK. Son of Leon Panetta (former CIA Director, Defense Secretary). Agricultural & coastal policy focus.", contact: "See website for internship application", about: "Work with Congressman representing California's Central Coast. Focus on agriculture, defense, environment, and veterans issues.", candidate: "College students interested in federal policy, constituent services, congressional operations.", skills: "Research, writing, constituent communication. Interest in agricultural and coastal policy.", materials: "See website for application requirements per term" },
  { company: "Representative Lateefah Simon (CA-12)", role: "Congressional Internship", category: "Government & Policy", paid: false, availability: "check", url: "https://simon.house.gov/services/internships", deadline: "Check website for current cycle", period: "Summer/Fall/Spring terms", location: "Oakland / Washington DC", undergradEligible: true, description: "✅ UNDERGRAD OK. NEW congresswoman (2025). Former BART Board Director, civil rights leader, MacArthur 'Genius' Grant winner.", contact: "See website for internship details", about: "Work with first-term Congresswoman focused on criminal justice reform, civil rights, and economic justice. Represents Oakland and parts of Contra Costa County.", candidate: "Students interested in criminal justice reform, civil rights, social justice, progressive politics.", skills: "Policy research, constituent services, community engagement. Passion for social justice.", materials: "Check website for application process" },
  { company: "Assemblymember Patrick Ahrens (AD-26)", role: "District Office Internship", category: "Government & Policy", paid: false, availability: "check", url: "https://a26.asmdc.org/assembly-district-26-internships", deadline: "Check website for term deadlines", period: "Varies by term", location: "Cupertino", undergradEligible: true, description: "✅ UNDERGRAD OK. VERY LOCAL — Cupertino! (5 miles from Palo Alto). State Assembly work close to Stanford/home.", contact: "See website for application", about: "California State Assembly representing Cupertino, Sunnyvale, Santa Clara. Work on state policy affecting Silicon Valley.", candidate: "Students interested in state government, California policy, tech regulation, local issues.", skills: "Legislative research, constituent services, policy analysis. Communication skills.", materials: "Check website for current application requirements" },
  { company: "Assemblymember Ash Kalra (AD-25)", role: "Assembly Internship", category: "Government & Policy", paid: false, availability: "check", url: "https://a25.asmdc.org/assembly-internship-opportunities", deadline: "Check website for term deadlines", period: "Varies by term", location: "San José", undergradEligible: true, description: "✅ UNDERGRAD OK. San Jose Assembly member. Progressive voice on criminal justice reform, workers' rights, housing.", contact: "See website for application", about: "State Assembly work with progressive leader. Focus on criminal justice reform, workers' rights, affordable housing.", candidate: "Students interested in progressive state policy, criminal justice reform, labor issues.", skills: "Policy research, legislative analysis, constituent engagement. Progressive values.", materials: "See website for application process" },
  { company: "Assemblymember Alex Lee (AD-24)", role: "Internship Program", category: "Government & Policy", paid: false, availability: "check", url: "https://a24.asmdc.org/internship-program", deadline: "Check website for term deadlines", period: "Varies by term", location: "Milpitas", undergradEligible: true, description: "✅ UNDERGRAD OK. Youngest CA legislator when elected (age 25). Progressive champion. Represents Milpitas/Fremont area.", contact: "See website for details", about: "Work with young progressive leader (first Gen Z state legislator in US). Focus on housing, climate, workers' rights.", candidate: "Students interested in progressive politics, youth in government, climate action, housing policy.", skills: "Social media savvy, policy research, grassroots organizing. Progressive values.", materials: "Check website for application requirements" },
  { company: "Senator Dave Cortese (SD-15)", role: "State Senate Internship", category: "Government & Policy", paid: false, availability: "check", url: "https://sd15.senate.ca.gov/", deadline: "Contact office for deadlines", period: "Varies by session", location: "San José / Sacramento", undergradEligible: true, description: "✅ UNDERGRAD OK. Represents Santa Clara County in State Senate. Former County Supervisor and San Jose Councilmember.", contact: "Contact district office", about: "State Senate work representing Santa Clara County. Focus on healthcare, education, environmental protection.", candidate: "Students interested in state government, healthcare policy, environmental issues.", skills: "Legislative research, policy analysis, constituent services. Interest in state-level policy.", materials: "Contact office for internship information" },
  { company: "Senator Scott Wiener (SD-11)", role: "State Senate Internship", category: "Government & Policy", paid: false, availability: "check", url: "https://sd11.senate.ca.gov/internship", deadline: "Check website for term deadlines", period: "Varies by session", location: "San Francisco / Sacramento", undergradEligible: true, description: "✅ UNDERGRAD OK. LGBTQ+ rights champion. Progressive leader on housing, transit, drug policy reform. SF-based.", contact: "See internship page", about: "Work with prominent progressive state senator. Leading voice on housing (YIMBY), LGBTQ+ rights, drug policy reform, transit.", candidate: "Students interested in progressive state policy, LGBTQ+ rights, housing, transit, criminal justice reform.", skills: "Policy research, constituent services, comfort with progressive advocacy on controversial issues.", materials: "See website for application process" },
  { company: "Silicon Valley Council of Nonprofits", role: "Nonprofit Sector Internship", category: "Nonprofits & Advocacy", paid: false, availability: "check", url: "https://www.svcn.org/job-board-pages/view-jobs", deadline: "Check job board for postings", period: "Varies", location: "San José area", undergradEligible: true, description: "✅ UNDERGRAD OK. Umbrella organization connecting nonprofits. Job board lists opportunities across many organizations.", contact: "See job board", about: "Resource hub for Silicon Valley nonprofits. Job board aggregates opportunities from many member organizations.", candidate: "Students interested in nonprofit sector, community development, social services.", skills: "Varies by posting. Generally: communication, project management, passion for nonprofit work.", materials: "Varies by organization — check individual postings" },
  { company: "ACLU of Northern California", role: "Internship Program", category: "Nonprofits & Advocacy", paid: false, availability: "check", url: "https://www.aclu.org/careers/internships/", deadline: "Check for current openings", period: "Summer/Academic year", location: "San Francisco", undergradEligible: true, description: "✅ UNDERGRAD OK. Premier civil liberties organization.", contact: "See ACLU careers page", about: "Work on civil liberties litigation, advocacy, and policy.", candidate: "Students passionate about constitutional rights.", skills: "Legal research, policy analysis, advocacy, writing.", materials: "Resume, cover letter, writing sample." },
  { company: "Asian Law Alliance", role: "Internship/Volunteer", category: "Nonprofits & Advocacy", paid: false, availability: "open", url: "https://www.asianlawalliance.org/get-involved", deadline: "Rolling applications", period: "Flexible", location: "San José", undergradEligible: true, description: "✅ UNDERGRAD OK. LOCAL — San Jose! Immigration, housing, employment law.", contact: "See website for volunteer/intern info", about: "Community-based legal services for Asian Americans and Pacific Islanders.", candidate: "Students interested in public interest law, immigrant rights.", skills: "Legal research, client interaction, bilingual abilities helpful.", materials: "Contact organization for volunteer/internship application" },
  { company: "Rep. Zoe Lofgren (CA-18)", role: "Congressional Internship", category: "Government & Policy", paid: false, availability: "open", url: "https://lofgren.house.gov/services/internships", deadline: "Rolling applications accepted", period: "Summer/Fall/Spring terms", location: "San José / Washington DC", undergradEligible: true, description: "✅ UNDERGRAD OK. 30+ years in Congress! Immigration and tech policy expert.", contact: "DC: internships.lofgren@mail.house.gov | District: lofgren.casework@mail.house.gov", about: "Work with senior member of Congress. Expert on immigration, tech policy, election law.", candidate: "Students interested in immigration policy, technology regulation.", skills: "Research, writing, constituent services.", materials: "Resume, cover letter, writing sample." },
  { company: "Bay Area Legal Aid", role: "Internship/Volunteer", category: "Nonprofits & Advocacy", paid: false, availability: "open", url: "https://baylegal.org/get-involved/volunteer/", deadline: "Rolling applications", period: "Flexible", location: "San José / Oakland / San Francisco", undergradEligible: true, description: "✅ UNDERGRAD OK. Free legal services for low-income residents.", contact: "See volunteer page", about: "Provide free legal services to low-income individuals. Housing, family law, consumer protection.", candidate: "Students interested in public interest law, social justice.", skills: "Legal research, client interaction, empathy. Bilingual helpful.", materials: "See website for volunteer/internship application" },
  { company: "Equal Rights Advocates", role: "Undergraduate Internship", category: "Nonprofits & Advocacy", paid: false, availability: "check", url: "https://www.equalrights.org/join-our-team/#undergrad-internships", deadline: "Check for current cycle", period: "Summer/Academic year", location: "San Francisco", undergradEligible: true, description: "✅ UNDERGRAD OK. Gender justice legal advocacy.", contact: "See website for application", about: "Legal advocacy for gender justice. Workplace discrimination, sexual harassment, equal pay.", candidate: "Undergraduate students interested in gender justice.", skills: "Legal research, policy analysis, client interaction.", materials: "See website for undergraduate internship application requirements" },
  { company: "Alameda County District Attorney", role: "Youth Employment Program", category: "Legal & Law", paid: true, availability: "check", url: "https://www.alcoda.org/community-outreach/youth-employment-programs/", deadline: "Check for current cycle", period: "Summer program", location: "Oakland", undergradEligible: true, description: "✅ UNDERGRAD OK. 💰 PAID youth employment program.", contact: "See website for program details", about: "Paid summer employment program with the Alameda County DA's Office.", candidate: "Undergraduate students interested in criminal justice.", skills: "Legal research, office administration, professionalism.", materials: "See website for youth employment application process" },
];

async function main() {
  console.log("Seeding database...");

  // Create demo users
  const hashedPwd = await bcrypt.hash("password123", 12);

  const abby = await prisma.user.upsert({
    where: { email: "abby@demo.com" },
    update: {},
    create: {
      name: "Abby",
      email: "abby@demo.com",
      hashedPassword: hashedPwd,
      field: "design",
      profile: {
        create: {
          school: "UCLA",
          graduationYear: 2029,
          major: "Design Media Arts",
          bio: "Freshman at UCLA studying Design Media Arts",
          interests: JSON.stringify(["UX Design", "Animation", "Game Art", "Motion Graphics", "Visual Design"]),
          locations: JSON.stringify(["Los Angeles", "San Francisco", "Remote"]),
        },
      },
    },
  });

  const son = await prisma.user.upsert({
    where: { email: "student@demo.com" },
    update: {},
    create: {
      name: "Student",
      email: "student@demo.com",
      hashedPassword: hashedPwd,
      field: "polisci",
      profile: {
        create: {
          school: "",
          graduationYear: 2028,
          major: "Political Science",
          bio: "Studying Political Science with focus on Bay Area government and policy",
          interests: JSON.stringify(["Government", "Criminal Justice", "Policy Research", "Civil Rights", "Campaigns"]),
          locations: JSON.stringify(["Palo Alto", "San José", "San Francisco", "Bay Area"]),
        },
      },
    },
  });

  console.log(`Created users: ${abby.name}, ${son.name}`);

  // Seed design internships
  for (const d of designInternships) {
    await prisma.internship.create({
      data: {
        field: "design",
        company: d.company,
        role: d.role,
        category: d.category,
        location: d.location,
        description: d.description,
        url: d.url,
        deadline: d.deadline,
        period: d.period,
        paid: d.paid,
        availability: d.availability,
        undergradEligible: d.undergradEligible,
        contact: d.contact,
        tooltipAbout: d.about,
        tooltipCandidate: d.candidate,
        tooltipSkills: d.skills,
        tooltipMaterials: d.materials,
      },
    });
  }
  console.log(`Seeded ${designInternships.length} design internships`);

  // Seed polisci internships
  for (const d of polisciInternships) {
    await prisma.internship.create({
      data: {
        field: "polisci",
        company: d.company,
        role: d.role,
        category: d.category,
        location: d.location,
        description: d.description,
        url: d.url,
        deadline: d.deadline,
        period: d.period,
        paid: d.paid,
        availability: d.availability,
        undergradEligible: d.undergradEligible,
        contact: d.contact,
        tooltipAbout: d.about,
        tooltipCandidate: d.candidate,
        tooltipSkills: d.skills,
        tooltipMaterials: d.materials,
      },
    });
  }
  console.log(`Seeded ${polisciInternships.length} polisci internships`);

  console.log("Seeding complete!");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
