import { PrismaClient } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import pg from "pg";
import bcrypt from "bcryptjs";

const DATABASE_URL = process.env.DATABASE_URL || "postgresql://neondb_owner:npg_NGmyBHTK9V4E@ep-still-credit-akb4pjfb-pooler.c-3.us-west-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require";
const pool = new pg.Pool({ connectionString: DATABASE_URL });
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

async function main() {
  // Clear existing data
  await prisma.notification.deleteMany();
  await prisma.userInternship.deleteMany();
  await prisma.internship.deleteMany();
  await prisma.profile.deleteMany();
  await prisma.user.deleteMany();

  // Create users
  const abby = await prisma.user.create({
    data: {
      id: "cmm78h10g00007ukmdt3y39az",
      name: "Abby",
      email: "abbycromwell2023@gmail.com",
      hashedPassword: await bcrypt.hash("password123", 10),
      field: "design",
    },
  });

  const kyle = await prisma.user.create({
    data: {
      id: "cmm78nsh3000224km4qldj77d",
      name: "Kyle Cromwell",
      email: "kylecromwell2023@gmail.com",
      hashedPassword: await bcrypt.hash("password123", 10),
      field: "polisci",
    },
  });

  // Create Abby's profile
  await prisma.profile.create({
    data: {
      id: "cmm78h10i00017ukm8n25a9z7",
      userId: abby.id,
      school: "UCLA",
      graduationYear: 2029,
      major: "Design Media Arts",
      bio: "Freshman at UCLA studying Design Media Arts",
      interests: JSON.stringify(["UX Design","Animation","Game Art","Motion Graphics","Visual Design"]),
      locations: JSON.stringify(["Los Angeles","San Francisco","Remote"]),
    },
  });

  // Create internships
  const internships = await Promise.all([
    prisma.internship.create({
      data: {
        id: "cmm78h10m00047ukmy8sv958f",
        field: "design",
        company: "Riot Games",
        role: "Internship Programs - Watch for 2027!",
        category: "Game Companies",
        location: "Remote (1 week at LA HQ)",
        description: "\ud83d\udcb0 $35-56/hr! \ud83c\udfae Summer 2026 roles closed (Jan 9). NEW roles post Sept 2026! Concept Art, Visual Design, 3D Art, Engineering. Remote with LA HQ week!",
        url: "https://www.riotgames.com/en/university-programs",
        deadline: "Applications open September 2026 for Summer 2027",
        period: "Summer 2027 (12 weeks, remote)",
        paid: true,
        availability: "soon",
        undergradEligible: true,
        contact: "Check riotgames.com/university-programs starting Sept 2026",
        tooltipAbout: "12-week remote internships across Riot. Past roles: Concept Art, Visual Design, 3D Environment Art, Software Engineering. Work on League, VALORANT, TFT, 2XKO. Includes 1 week at LA HQ!",
        tooltipCandidate: "Graduating 2027-2028. Strong portfolio required for art/design roles. Passion for Riot games essential.",
        tooltipSkills: "Varies by role: Character/environment art, UI/UX design (Figma), 3D modeling, programming.",
        tooltipMaterials: "Resume, portfolio/demo reel. Applications evaluated rolling basis. Apply early when positions open in September!",
        active: true,
      },
    }),
    prisma.internship.create({
      data: {
        id: "cmm78h10n00057ukmxh0kps0c",
        field: "design",
        company: "Netflix",
        role: "Creative Innovation Intern",
        category: "Media & Entertainment",
        location: "Los Angeles (relocation + housing support provided!)",
        description: "\ud83d\udcb0 $40-110/hr! \ud83c\udfac URGENT - Closes Feb 6! Work with Content Operations & Innovation. Relocation + housing support!",
        url: "https://explore.jobs.netflix.net/careers/job/790313701820",
        deadline: "February 6, 2026 - APPLY NOW!",
        period: "Summer 2026 (12 weeks)",
        paid: true,
        availability: "open",
        undergradEligible: true,
        contact: "Apply through explore.jobs.netflix.net",
        tooltipAbout: "Support creative and production innovation at Netflix. Research emerging media/production tech, evaluate new tools, create workflows for creative teams.",
        tooltipCandidate: "Enrolled in university (bachelor's or master's). Graduating Dec 2026 or Spring 2027. Passion for GenAI and creative tools.",
        tooltipSkills: "Research, analysis, communication, workflow design. Interest in emerging technologies and creative tools.",
        tooltipMaterials: "Resume. Answer essay question about evaluating new tools for Netflix. Applications close Feb 6, 2026!",
        active: true,
      },
    }),
    prisma.internship.create({
      data: {
        id: "cmm78h10o00067ukm3s6y6ro0",
        field: "design",
        company: "Netflix",
        role: "Summer Internship Programs (General)",
        category: "Media & Entertainment",
        location: "Los Gatos or Los Angeles",
        description: "\ud83d\udcb0 $40-110/hr! \ud83c\udfac Multiple roles: Engineering, Data, Content, Marketing. Postings usually start Aug/Sept!",
        url: "https://jobs.netflix.com/careers/internships",
        deadline: "Applications typically open late summer/early fall",
        period: "Summer 2026 (12 weeks minimum)",
        paid: true,
        availability: "check",
        undergradEligible: true,
        contact: "Apply through jobs.netflix.com/careers/internships",
        tooltipAbout: "12-week summer internships across Engineering, Data & Insights, Content, Finance & Strategy, Marketing.",
        tooltipCandidate: "Enrolled in bachelor's, master's, or doctoral programs. Passion for entertainment/tech.",
        tooltipSkills: "Varies by role - technical for engineering/data, creative for content/marketing.",
        tooltipMaterials: "Resume, sometimes portfolio or take-home assessment. Check site starting August 2026!",
        active: true,
      },
    }),
    prisma.internship.create({
      data: {
        id: "cmm78h10p00077ukmd9a9u2kd",
        field: "design",
        company: "Roblox",
        role: "Content Design Intern",
        category: "Game Companies",
        location: "San Mateo (hybrid - Tue/Wed/Thu in office)",
        description: "\ud83d\udcb0 Competitive pay! \ud83c\udfae CURRENTLY OPEN! Craft user experiences for 111M+ daily users.",
        url: "https://careers.roblox.com/jobs/7612803",
        deadline: "Rolling applications",
        period: "Summer 2026 (12 weeks)",
        paid: true,
        availability: "open",
        undergradEligible: true,
        contact: "Apply through careers.roblox.com",
        tooltipAbout: "Work within Design and Creative team alongside product managers and engineers.",
        tooltipCandidate: "Enrolled in undergrad/grad in English, Communications, HCI, Design, or related field.",
        tooltipSkills: "Content design, UX writing, information architecture, design thinking.",
        tooltipMaterials: "Resume, portfolio. Sign up for Speak_ platform for practice assessments.",
        active: true,
      },
    }),
    prisma.internship.create({
      data: {
        id: "cmm78h10q00087ukmkqfrl20e",
        field: "design",
        company: "Roblox",
        role: "Software Engineering Intern",
        category: "Game Companies",
        location: "San Mateo (hybrid - Tue/Wed/Thu in office)",
        description: "\ud83d\udcb0 High pay! \ud83c\udfae For CS/tech students. Work on platform serving 111M+ daily users.",
        url: "https://careers.roblox.com/jobs/7114765",
        deadline: "Rolling applications",
        period: "Summer 2026 (12 weeks)",
        paid: true,
        availability: "open",
        undergradEligible: true,
        contact: "Apply through careers.roblox.com",
        tooltipAbout: "Join supportive software engineering team. Deliver work to production.",
        tooltipCandidate: "Pursuing degree in CS, engineering, or tech-related field.",
        tooltipSkills: "Programming, data structures, algorithms, object-oriented programming.",
        tooltipMaterials: "Resume, portfolio/GitHub. Use Speak_ platform for preparation.",
        active: true,
      },
    }),
    prisma.internship.create({
      data: {
        id: "cmm78h10r00097ukm1fvn9otn",
        field: "design",
        company: "Roblox",
        role: "Associate Product Designer (21-month program)",
        category: "Game Companies",
        location: "San Mateo (hybrid - Tue/Wed/Thu in office)",
        description: "\ud83d\udcb0 Competitive! \ud83c\udfae 21-MONTH rotational program for new grads! Design for 111M users.",
        url: "https://careers.roblox.com/jobs/7167345",
        deadline: "Rolling applications for 2026 start",
        period: "21-month rotational program starting 2026",
        paid: true,
        availability: "open",
        undergradEligible: true,
        contact: "Apply through careers.roblox.com",
        tooltipAbout: "21-month rotational program for early career designers. Direct mentorship from industry-leading designers.",
        tooltipCandidate: "Possess or will possess undergrad/grad degree in UX/UI, Interaction, Motion, Graphics, Typography, Web, or Product Design.",
        tooltipSkills: "UX/UI design, prototyping, user research, competitive analysis. Design systems.",
        tooltipMaterials: "Resume, portfolio required. Shows: features, prototypes, research process.",
        active: true,
      },
    }),
    prisma.internship.create({
      data: {
        id: "cmm78h10r000a7ukmv36gvnvw",
        field: "design",
        company: "Sony Pictures Animation",
        role: "Marketing Intern",
        category: "Animation & VFX",
        location: "Culver City, CA",
        description: "\ud83d\udcb0 $19/hr! \ud83c\udfac 5-week PAID program. Work on campaigns for SPA films! Deadline approaching!",
        url: "https://www.sonypicturesanimation.com/careers/job-postings",
        deadline: "Applications close February 27, 2026",
        period: "Summer 2026 (5 weeks, full-time)",
        paid: true,
        availability: "soon",
        undergradEligible: true,
        contact: "Apply through Sony Pictures jobs site",
        tooltipAbout: "Support Marketing team in developing and executing campaigns for Sony Pictures Animation films.",
        tooltipCandidate: "Students interested in animation marketing, branding, creative campaigns.",
        tooltipSkills: "Campaign planning, research, creative marketing, brand integration.",
        tooltipMaterials: "Resume, cover letter. Deadline Feb 27, 2026!",
        active: true,
      },
    }),
    prisma.internship.create({
      data: {
        id: "cmm78h10s000b7ukmh0wsttvb",
        field: "design",
        company: "Sony Pictures Animation",
        role: "Creative Group Intern",
        category: "Animation & VFX",
        location: "Culver City, CA",
        description: "\ud83c\udfac Work with executives who develop and oversee animated movies!",
        url: "https://www.sonypicturesanimation.com/careers/job-postings",
        deadline: "Check for Summer 2026 postings (Spring posted Jan-Apr)",
        period: "Varies by term",
        paid: true,
        availability: "check",
        undergradEligible: true,
        contact: "Apply through Sony Pictures careers",
        tooltipAbout: "Work with creative executives who develop and oversee theatrical animated films.",
        tooltipCandidate: "Students in film, animation, entertainment, or related fields.",
        tooltipSkills: "Script analysis, research, note-taking, presentation building.",
        tooltipMaterials: "Resume, cover letter. Check sonypicturesjobs.com regularly.",
        active: true,
      },
    }),
    prisma.internship.create({
      data: {
        id: "cmm78h10t000c7ukmbminfn89",
        field: "design",
        company: "Sony Pictures Imageworks",
        role: "Internship Program (iCAD)",
        category: "Animation & VFX",
        location: "Vancouver, Canada",
        description: "\ud83c\udfac World-class VFX studio! Must be eligible to work in Canada.",
        url: "https://www.imageworks.com/icad/internships",
        deadline: "Check website for application periods",
        period: "Summer (paid internship)",
        paid: true,
        availability: "check",
        undergradEligible: true,
        contact: "Apply through Imageworks careers",
        tooltipAbout: "Get paid to learn from industry leaders. Work on live action or CG animated feature films.",
        tooltipCandidate: "Recent graduates and current students. Must be eligible to work in Canada.",
        tooltipSkills: "Computer animation, digital arts, computer science.",
        tooltipMaterials: "Resume, demo reel/portfolio. Review 'Reel Advice' on website.",
        active: true,
      },
    }),
    prisma.internship.create({
      data: {
        id: "cmm78h10u000d7ukmbbm8xoev",
        field: "design",
        company: "Pixar Animation Studios",
        role: "Art Department Intern",
        category: "Animation & VFX",
        location: "Emeryville, CA (Bay Area!)",
        description: "\ud83d\udcb0 $22.50/hr! \ud83c\udfac DREAM OPPORTUNITY at Pixar! Character Design, Set Design, Color/Shading, or Graphic Design tracks.",
        url: "https://www.disneycareers.com/en/job/emeryville/art-department-intern-summer-2026/391/89182146960",
        deadline: "Check Disney Careers for deadlines (typically winter/spring)",
        period: "Summer 2026 (12 weeks)",
        paid: true,
        availability: "check",
        undergradEligible: true,
        contact: "Apply through Disney Careers",
        tooltipAbout: "Work with mentors and Art Department gaining feature film experience.",
        tooltipCandidate: "Interest in visual storytelling. Strengths in illustration, drawing, painting, animation.",
        tooltipSkills: "Choose ONE focus: Character Design, Set Design, Color/Shading/Lighting Design, or Graphic Design.",
        tooltipMaterials: "Single PDF: resume + cover letter. Portfolio/demo reel link required.",
        active: true,
      },
    }),
    prisma.internship.create({
      data: {
        id: "cmm78h10u000e7ukmrrzfcxze",
        field: "design",
        company: "Pixar Animation Studios",
        role: "Product Design Intern",
        category: "Animation & VFX",
        location: "Emeryville, CA (Bay Area!)",
        description: "\ud83d\udcb0 $41.40/hr! \ud83c\udfac INCREDIBLE PAY! UX/UI/product design for film tech.",
        url: "https://www.disneycareers.com/en/job/emeryville/product-design-intern-summer-2026/391/89182147008",
        deadline: "Check Disney Careers (typically posted late fall-spring)",
        period: "Summer 2026 (12 weeks)",
        paid: true,
        availability: "check",
        undergradEligible: true,
        contact: "Apply through Disney Careers",
        tooltipAbout: "Contribute to product innovation. Work on products used in Pixar's filmmaking process.",
        tooltipCandidate: "Pursuing degree in design, HCI, or related field.",
        tooltipSkills: "Product design, UX/UI, prototyping, user research.",
        tooltipMaterials: "Resume, portfolio. Check pixar.com/careers regularly.",
        active: true,
      },
    }),
    prisma.internship.create({
      data: {
        id: "cmm78h10v000f7ukmngqu46t5",
        field: "design",
        company: "Walt Disney Animation Studios",
        role: "Internship & Apprenticeship Programs",
        category: "Animation & VFX",
        location: "Burbank, CA",
        description: "\ud83c\udfac Legacy Disney animation! Craft-based mentorship from Disney artists/engineers.",
        url: "https://disneyanimation.com/interns-apprentices/",
        deadline: "Internships posted late fall-spring; Apprenticeships year-round",
        period: "10-12 weeks (internships)",
        paid: true,
        availability: "check",
        undergradEligible: true,
        contact: "Apply through Disney Animation careers",
        tooltipAbout: "Mentored opportunities across production, technology, and studio teams.",
        tooltipCandidate: "Students and recent graduates. Passion for animation storytelling.",
        tooltipSkills: "Varies by role - production, art, animation, technology.",
        tooltipMaterials: "Portfolio essential - showcase versatility and originality.",
        active: true,
      },
    }),
    prisma.internship.create({
      data: {
        id: "cmm78h10w000g7ukmcia9nwc5",
        field: "design",
        company: "Disney",
        role: "Graphic Design Intern (D+/Disney Bundle)",
        category: "Media & Entertainment",
        location: "Burbank, CA",
        description: "\ud83d\udcb0 $22.50/hr! \ud83c\udfac Design for Disney+ and Disney Bundle!",
        url: "https://www.disneycareers.com/en/job/burbank/d-graphic-design-intern-summer-2026/391/90960654096",
        deadline: "Check Disney Careers for deadline",
        period: "Summer 2026 (June-August)",
        paid: true,
        availability: "check",
        undergradEligible: true,
        contact: "Apply through Disney Careers",
        tooltipAbout: "Create designs for Disney+ and Disney Bundle following brand style guides.",
        tooltipCandidate: "Majoring in graphic design, digital design, entertainment design.",
        tooltipSkills: "Adobe Creative Suite, Google Suite, Microsoft Office.",
        tooltipMaterials: "Portfolio required (website or PDF).",
        active: true,
      },
    }),
    prisma.internship.create({
      data: {
        id: "cmm78h10w000h7ukmticuu0iu",
        field: "design",
        company: "Disney Consumer Products",
        role: "Character Art Intern",
        category: "Design Studios",
        location: "Glendale, CA",
        description: "\ud83c\udfa8 Design Disney characters for consumer products!",
        url: "https://www.disneycareers.com/en/internships-united-states",
        deadline: "Check Disney Careers",
        period: "Summer/Fall 2026 (3-6 months)",
        paid: true,
        availability: "check",
        undergradEligible: true,
        contact: "Apply through Disney Careers",
        tooltipAbout: "Create character art for Disney Consumer Products.",
        tooltipCandidate: "Art/design students passionate about Disney characters.",
        tooltipSkills: "Character design, illustration, digital art.",
        tooltipMaterials: "Portfolio required. Resume.",
        active: true,
      },
    }),
    prisma.internship.create({
      data: {
        id: "cmm78h10x000i7ukmmaijpsbb",
        field: "design",
        company: "Blizzard Entertainment",
        role: "Check for Summer Internships",
        category: "Game Companies",
        location: "Irvine, CA",
        description: "\ud83c\udfae Creators of Overwatch, World of Warcraft, Diablo!",
        url: "https://careers.blizzard.com/",
        deadline: "Varies - check careers site",
        period: "Summer 2026",
        paid: true,
        availability: "check",
        undergradEligible: true,
        contact: "Apply through Blizzard careers",
        tooltipAbout: "Leading game company known for Overwatch, WoW, Diablo.",
        tooltipCandidate: "Game design, art, animation students.",
        tooltipSkills: "Varies by role - concept art, 3D modeling, animation, UI/UX.",
        tooltipMaterials: "Resume, portfolio/demo reel.",
        active: true,
      },
    }),
    prisma.internship.create({
      data: {
        id: "cmm78h10y000j7ukm2ik654dy",
        field: "design",
        company: "Electronic Arts (EA)",
        role: "Design/Art Internships",
        category: "Game Companies",
        location: "Various (LA, Bay Area, etc.)",
        description: "\ud83c\udfae Major game publisher! FIFA, Apex Legends, The Sims, etc.",
        url: "https://www.ea.com/careers/interns-and-university-graduates",
        deadline: "Typically open fall/winter for summer",
        period: "Summer 2026 (12 weeks)",
        paid: true,
        availability: "check",
        undergradEligible: true,
        contact: "Apply through EA careers",
        tooltipAbout: "Work on major franchises like FIFA, Madden, Apex Legends, The Sims.",
        tooltipCandidate: "Game design/art students. Portfolio required.",
        tooltipSkills: "Varies - concept art, 3D art, animation, UI/UX.",
        tooltipMaterials: "Resume, portfolio. Applications typically open late fall.",
        active: true,
      },
    }),
    prisma.internship.create({
      data: {
        id: "cmm78h10z000k7ukmvzlklpcc",
        field: "design",
        company: "BUCK (Design Studio)",
        role: "Check for Internship Programs",
        category: "Design Studios",
        location: "Los Angeles, NY",
        description: "\ud83c\udfa8 Prestigious design/animation studio! Motion graphics, 3D animation.",
        url: "https://buck.co/careers",
        deadline: "Varies",
        period: "Varies",
        paid: false,
        availability: "check",
        undergradEligible: true,
        contact: "careers@buck.co",
        tooltipAbout: "Leading creative studio specializing in design, animation, motion graphics.",
        tooltipCandidate: "Motion design, animation, graphic design students.",
        tooltipSkills: "Motion graphics, 3D animation, After Effects, Cinema 4D.",
        tooltipMaterials: "Check buck.co/careers for current openings.",
        active: true,
      },
    }),
    prisma.internship.create({
      data: {
        id: "cmm78h111000l7ukmpuxjxzci",
        field: "design",
        company: "Method Studios / Framestore",
        role: "VFX Internships",
        category: "Animation & VFX",
        location: "Los Angeles, Vancouver",
        description: "\ud83c\udfac Major VFX studios! Work on blockbuster films and TV shows.",
        url: "https://www.methodstudios.com/careers",
        deadline: "Check careers sites",
        period: "Varies",
        paid: false,
        availability: "check",
        undergradEligible: true,
        contact: "Apply through respective careers sites",
        tooltipAbout: "VFX and animation for major films and TV.",
        tooltipCandidate: "VFX, animation, or related students.",
        tooltipSkills: "VFX, compositing, 3D modeling, animation. Maya, Nuke, Houdini.",
        tooltipMaterials: "Demo reel, resume.",
        active: true,
      },
    }),
    prisma.internship.create({
      data: {
        id: "cmm78h111000m7ukmi2ynew85",
        field: "design",
        company: "DreamWorks Animation",
        role: "Check for Internship Programs",
        category: "Animation & VFX",
        location: "Glendale, CA",
        description: "\ud83c\udfac How to Train Your Dragon, Kung Fu Panda, Shrek!",
        url: "https://www.dreamworks.com/jobs",
        deadline: "Check careers site",
        period: "Summer typically",
        paid: true,
        availability: "check",
        undergradEligible: true,
        contact: "Apply through DreamWorks careers",
        tooltipAbout: "Major animation studio creating beloved films.",
        tooltipCandidate: "Animation, art, or related students.",
        tooltipSkills: "Varies - animation, character/environment art, rigging, lighting.",
        tooltipMaterials: "Portfolio/demo reel required.",
        active: true,
      },
    }),
    prisma.internship.create({
      data: {
        id: "cmm78h112000n7ukm5pzr2ykc",
        field: "design",
        company: "Sephora",
        role: "Visual Design Intern",
        category: "Creative Agencies",
        location: "Remote (CA) + 1 week in San Francisco HQ",
        description: "\ud83d\udcb0 $25/hr! \ud83d\udc84 CURRENTLY OPEN! Remote + paid SF week! Create graphics for eLearning, mobile/desktop.",
        url: "https://join.sephora.com/careers/job/790299319018",
        deadline: "Rolling applications",
        period: "Summer 2026 (10 weeks: June 1 - August 14)",
        paid: true,
        availability: "open",
        undergradEligible: true,
        contact: "Apply through join.sephora.com",
        tooltipAbout: "Support Retail Engagement team. Create compelling graphics and interactive elements.",
        tooltipCandidate: "Pursuing degree in Graphic Design, Visual Design, or related field.",
        tooltipSkills: "Adobe Creative Suite (Illustrator, Photoshop, InDesign), visual design.",
        tooltipMaterials: "Resume, portfolio showcasing visual design work.",
        active: true,
      },
    }),
    prisma.internship.create({
      data: {
        id: "cmm78h113000o7ukmylb04ibn",
        field: "design",
        company: "Sephora",
        role: "Summer Internship Program (Multiple Roles)",
        category: "Creative Agencies",
        location: "Remote (CA) + 1 week in San Francisco",
        description: "\ud83d\udcb0 $25/hr! \ud83d\udc84 Multiple roles: Marketing, Merchandising, Finance, Engineering.",
        url: "https://www.inside-sephora.com/en/usa/sephora-internships",
        deadline: "Rolling - applications opened October 2025",
        period: "Summer 2026 (10 weeks)",
        paid: true,
        availability: "open",
        undergradEligible: true,
        contact: "Apply through inside-sephora.com or join.sephora.com",
        tooltipAbout: "10-week paid corporate internship program. Work on impactful projects.",
        tooltipCandidate: "Graduating 2026 or 2027. All majors welcome.",
        tooltipSkills: "Varies by role - design, marketing, merchandising, engineering.",
        tooltipMaterials: "Resume. Check inside-sephora.com for specific roles.",
        active: true,
      },
    }),
    prisma.internship.create({
      data: {
        id: "cmm78h113000p7ukmubzxm6u8",
        field: "design",
        company: "Vercel",
        role: "Engineering Summer Intern",
        category: "Tech/Product Design",
        location: "Remote - work across time zones",
        description: "\ud83d\udcb0 $9,500-$11,000/month! \ud83d\ude80 Work on Next.js, v0, AI SDK! Design engineering opportunities!",
        url: "https://vercel.com/careers/engineering-summer-intern-5628292004",
        deadline: "Rolling applications",
        period: "Summer 2026 (12 weeks typical)",
        paid: true,
        availability: "open",
        undergradEligible: true,
        contact: "Apply through vercel.com/careers",
        tooltipAbout: "Work on REAL production projects at Vercel - creators of Next.js, v0 (AI design tool), and AI SDK.",
        tooltipCandidate: "Pursuing degree in Computer Science, Engineering, or related field.",
        tooltipSkills: "JavaScript, TypeScript. Next.js, React. 'Design engineering' mindset.",
        tooltipMaterials: "Resume. Perfect for DMA students who code!",
        active: true,
      },
    }),
    prisma.internship.create({
      data: {
        id: "cmm78h115000q7ukmcbwll8v4",
        field: "design",
        company: "Warner Bros. Discovery",
        role: "Design Internships (Multiple Locations)",
        category: "Media & Entertainment",
        location: "LA, NYC, Atlanta, Burbank (hybrid)",
        description: "\u26a0\ufe0f DEADLINE PASSED (Feb 22)! Next year: Apply early Fall 2026 for Summer 2027.",
        url: "https://careers.wbd.com/global/en/c/early-careers-jobs",
        deadline: "February 22, 2026 - PASSED",
        period: "Summer 2026 (11 weeks)",
        paid: true,
        availability: "closed",
        undergradEligible: true,
        contact: "careers.wbd.com",
        tooltipAbout: "Award-winning global internship program. HBO, CNN, Max, Bleacher Report, TLC, Food Network.",
        tooltipCandidate: "Rising Junior, Senior, or Graduate Student. 3.0+ GPA required.",
        tooltipSkills: "Adobe Creative Suite, Figma. Strong design and typography skills.",
        tooltipMaterials: "Resume + portfolio. For 2027: Set alert on careers.wbd.com in September 2026!",
        active: true,
      },
    }),
    prisma.internship.create({
      data: {
        id: "cmm78h116000r7ukmk2v7d1kw",
        field: "design",
        company: "Warner Bros. Discovery",
        role: "WB Animation - Creative Services (Graphic Design)",
        category: "Animation & VFX",
        location: "Burbank, CA (hybrid)",
        description: "\u26a0\ufe0f DEADLINE PASSED! Next summer: Apply Fall 2026.",
        url: "https://careers.wbd.com/global/en/c/early-careers-jobs",
        deadline: "February 22, 2026 - PASSED",
        period: "Summer 2026 (11 weeks)",
        paid: true,
        availability: "closed",
        undergradEligible: true,
        contact: "careers.wbd.com",
        tooltipAbout: "Warner Bros. Animation Creative Services team.",
        tooltipCandidate: "Rising Junior, Senior, or Grad Student. 3.0+ GPA.",
        tooltipSkills: "Adobe Creative Suite. Typography skills. Brand design.",
        tooltipMaterials: "Resume + graphic design portfolio.",
        active: true,
      },
    }),
    prisma.internship.create({
      data: {
        id: "cmm78h117000s7ukmwm3sms6h",
        field: "design",
        company: "Fuser",
        role: "Brand & Motion Design Intern",
        category: "Creative Agencies",
        location: "Hybrid - Los Angeles (1 day/week in office)",
        description: "\ud83d\udcb0 $37k-$42k (6 months)! \ud83c\udfac CURRENTLY OPEN! AI creative tool company!",
        url: "https://fuser.studio/careers",
        deadline: "Rolling applications",
        period: "6 months (potential for full-time conversion)",
        paid: true,
        availability: "open",
        undergradEligible: true,
        contact: "Apply through fuser.studio/careers",
        tooltipAbout: "Creative technology company building AI-powered collaborative canvas.",
        tooltipCandidate: "Emerging designers who think in movement and systems.",
        tooltipSkills: "Figma, Photoshop, + at least one motion tool (After Effects, Cavalry, Rive).",
        tooltipMaterials: "Portfolio with process work. Potential to convert to full-time!",
        active: true,
      },
    }),
    prisma.internship.create({
      data: {
        id: "cmm78h118000t7ukm4jkes0ar",
        field: "design",
        company: "Figma",
        role: "Product Design Intern",
        category: "Tech/Product Design",
        location: "San Francisco or New York (in-person required)",
        description: "\ud83c\udfa8 CURRENTLY OPEN! Own impactful projects from ideation to execution! Housing stipend + travel reimbursement.",
        url: "https://job-boards.greenhouse.io/figma/jobs/5616453004",
        deadline: "Applications typically open fall for following summer",
        period: "Summer 2026 (dates TBD)",
        paid: true,
        availability: "open",
        undergradEligible: true,
        contact: "Apply through job-boards.greenhouse.io/figma",
        tooltipAbout: "OWN real impactful projects from start to finish at Figma!",
        tooltipCandidate: "Demonstrated baseline in visual design and/or interaction design.",
        tooltipSkills: "Visual design, interaction design, prototyping, product strategy.",
        tooltipMaterials: "Portfolio showcasing design excellence and creative process.",
        active: true,
      },
    }),
    prisma.internship.create({
      data: {
        id: "cmm78h118000u7ukmw0xk1kxw",
        field: "design",
        company: "Hasbro",
        role: "Graphic Design Intern - Games",
        category: "Design Studios",
        location: "Pawtucket, RI (in-person required)",
        description: "\ud83d\udcb0 $27/hr! \ud83c\udfb2 CURRENTLY OPEN! Design board games! Monopoly, Nerf, Transformers!",
        url: "https://jobs.hasbro.com/content/student-programs/?locale=en_US",
        deadline: "Interview Timeline: February - April 2026",
        period: "11 weeks (June 8 - August 21, 2026)",
        paid: true,
        availability: "open",
        undergradEligible: true,
        contact: "Apply through jobs.hasbro.com",
        tooltipAbout: "Work with Hasbro's Games creative team on game components, box design, rules layout.",
        tooltipCandidate: "Currently enrolled in Graphic Design, Fine Arts, or related degree.",
        tooltipSkills: "HIGHLY proficient in: Illustrator, Photoshop, Acrobat, InDesign.",
        tooltipMaterials: "Portfolio showing graphic design work. Resume.",
        active: true,
      },
    }),
    prisma.internship.create({
      data: {
        id: "cmm78h119000v7ukm7tjmt7l4",
        field: "design",
        company: "Mattel / Fisher-Price",
        role: "Summer Internship Program - Check for Design Roles",
        category: "Design Studios",
        location: "El Segundo, CA (HQ) - some hybrid options",
        description: "\ud83e\uddf8 Design toys for iconic brands! Barbie, Hot Wheels, Fisher-Price!",
        url: "https://jobs.mattel.com/en/category/internship-jobs/2015/61215/1",
        deadline: "Applications typically open late fall/early winter",
        period: "10-12 weeks Summer 2026",
        paid: true,
        availability: "check",
        undergradEligible: true,
        contact: "Apply through jobs.mattel.com",
        tooltipAbout: "Mattel's internship program for future leaders! Barbie, Hot Wheels, Fisher-Price, American Girl.",
        tooltipCandidate: "Enrolled undergraduate/graduate students. Passion for toys and entertainment.",
        tooltipSkills: "Adobe Photoshop, Illustrator. 3D modeling software is a plus.",
        tooltipMaterials: "Resume + cover letter. Portfolio required for design roles.",
        active: true,
      },
    }),
    prisma.internship.create({
      data: {
        id: "cmm78h11a000w7ukmrgg78klm",
        field: "design",
        company: "TikTok",
        role: "Product Designer Intern (TikTok-Design-UX)",
        category: "Tech/Product Design",
        location: "San Jose, CA",
        description: "\ud83d\udcb0 $30/hr + housing allowance! \ud83d\udcf1 CURRENTLY OPEN! Design for global short-video platform!",
        url: "https://lifeattiktok.com/search/7533145462880127240",
        deadline: "Rolling applications - apply early!",
        period: "12 weeks Summer 2026",
        paid: true,
        availability: "open",
        undergradEligible: true,
        contact: "Apply through lifeattiktok.com - Max 2 positions",
        tooltipAbout: "Design for TikTok's creative short video platform targeting global users.",
        tooltipCandidate: "Pursuing undergraduate or graduate degree. MUST submit portfolio.",
        tooltipSkills: "Interaction design, Figma prototyping.",
        tooltipMaterials: "Resume with CLEAR availability. PORTFOLIO REQUIRED.",
        active: true,
      },
    }),
    prisma.internship.create({
      data: {
        id: "cmm78h11c000x7ukm734vxtiq",
        field: "design",
        company: "Hasbro",
        role: "Graphic Design Intern (Games)",
        category: "Game Companies",
        location: "Pawtucket, RI (in-person required)",
        description: "\ud83d\udcb0 $24-27/hr! \ud83c\udfb2 CURRENTLY OPEN! Work on Games creative projects.",
        url: "https://jobs.hasbro.com/go/Internships-&-Co-ops/8206000/",
        deadline: "Rolling applications",
        period: "11 weeks (June 8 - August 21, 2026)",
        paid: true,
        availability: "open",
        undergradEligible: true,
        contact: "Apply through jobs.hasbro.com",
        tooltipAbout: "11-week paid internship working on Games creative projects.",
        tooltipCandidate: "Enrolled in Graphic Design, Fine Arts, or related.",
        tooltipSkills: "Illustrator, Photoshop, Acrobat, InDesign.",
        tooltipMaterials: "Resume. Portfolio recommended.",
        active: true,
      },
    }),
    prisma.internship.create({
      data: {
        id: "cmm78h11d000y7ukmzlbge4ww",
        field: "design",
        company: "Hasbro",
        role: "Product Design Co-op (Action Brands)",
        category: "Game Companies",
        location: "Pawtucket, RI (in-person)",
        description: "\ud83d\udcb0 $29-33/hr! \ud83c\udfae CURRENTLY OPEN! Design TOYS for Star Wars, Transformers, G.I. Joe!",
        url: "https://jobs.hasbro.com/go/Internships-&-Co-ops/8206000/",
        deadline: "Rolling applications",
        period: "Summer/Fall 2026",
        paid: true,
        availability: "open",
        undergradEligible: true,
        contact: "Apply through jobs.hasbro.com",
        tooltipAbout: "Hasbro Action Brands team. Ideating play experiences, visualizing toy concepts, prototyping.",
        tooltipCandidate: "Creative students passionate about toys and action figures.",
        tooltipSkills: "Product design/development. Creative problem solving.",
        tooltipMaterials: "Resume + portfolio.",
        active: true,
      },
    }),
    prisma.internship.create({
      data: {
        id: "cmm78h11d000z7ukm82tnxfdh",
        field: "design",
        company: "Notion",
        role: "Software Engineer Intern (Design Engineering)",
        category: "Tech/Product Design",
        location: "San Francisco or New York (in-person required)",
        description: "\ud83d\udcbb CURRENTLY OPEN! Design-first company! Ship real features to millions!",
        url: "https://jobs.ashbyhq.com/notion/23ac2477-0008-4bed-b1c1-81f90a32e9e6",
        deadline: "Rolling applications",
        period: "12 weeks (May - September 2026)",
        paid: true,
        availability: "open",
        undergradEligible: true,
        contact: "Apply through jobs.ashbyhq.com/notion",
        tooltipAbout: "Work on real projects that ship to production! Design-first philosophy.",
        tooltipCandidate: "Pursuing Bachelor's/Master's in CS, Engineering, or related.",
        tooltipSkills: "TypeScript, Node.js, Go, Python. CSS, JavaScript, React.",
        tooltipMaterials: "Resume. MUST be able to work in-person.",
        active: true,
      },
    }),
    prisma.internship.create({
      data: {
        id: "cmm78h11e00107ukma2d6wvdq",
        field: "design",
        company: "Notion",
        role: "UX Research Intern",
        category: "Tech/Product Design",
        location: "San Francisco (in-person required)",
        description: "\ud83d\udd2c Research how users discover/adopt Calendar, Mail, AI! Graduate students only.",
        url: "https://jobs.ashbyhq.com/notion/2e7b83cd-9210-4492-ad30-7b898b80807b",
        deadline: "Rolling applications",
        period: "Full-time (May - September 2026)",
        paid: true,
        availability: "open",
        undergradEligible: false,
        contact: "Apply through jobs.ashbyhq.com/notion",
        tooltipAbout: "Research user discovery and adoption of Notion's expanding ecosystem.",
        tooltipCandidate: "Master's or PhD in HCI, Psychology, Cognitive Science.",
        tooltipSkills: "Research methods (qualitative/quantitative). Product sense.",
        tooltipMaterials: "Resume showing research experience.",
        active: true,
      },
    }),
    prisma.internship.create({
      data: {
        id: "cmm78h11f00117ukm5fguq3tz",
        field: "polisci",
        company: "SF City Attorney's Office",
        role: "Summer Internship Program",
        category: "Legal & Law",
        location: "San Francisco",
        description: "\u26a0\ufe0f LAW STUDENTS ONLY. Rolling admissions, still open! Pick 3 preferred practice teams.",
        url: "https://sfcityattorney.org/aboutus/internships/",
        deadline: "Rolling \u2014 accepting until filled",
        period: "Summer 2026 (10 weeks, full-time)",
        paid: false,
        availability: "open",
        undergradEligible: false,
        contact: "Allie.Saperstein@sfcityatty.org",
        tooltipAbout: "Nationally ABA-recognized municipal law office. Work across 100+ city departments on real legal matters.",
        tooltipCandidate: "Law students only (summer full-time). Seeking future leaders in government and public-interest law.",
        tooltipSkills: "Legal research, writing, interest in municipal government & public interest law.",
        tooltipMaterials: "Cover letter, resume, brief legal writing sample.",
        active: false,
      },
    }),
    prisma.internship.create({
      data: {
        id: "cmm78h11g00137ukmlwmqdi1v",
        field: "polisci",
        company: "CA Attorney General's Office",
        role: "Student Intern / Volunteer",
        category: "Government & Policy",
        location: "San Francisco / Sacramento",
        description: "\u2705 UNDERGRAD OK. State-level DOJ experience. Multiple divisions.",
        url: "https://oag.ca.gov/careers/students",
        deadline: "Currently accepting \u2014 multiple positions listed",
        period: "Varies by position (summer and ongoing)",
        paid: false,
        availability: "open",
        undergradEligible: true,
        contact: "See individual listings at oag.ca.gov/careers/students",
        tooltipAbout: "Work within the CA Department of Justice. Divisions include public safety, civil rights, consumer protection.",
        tooltipCandidate: "Currently enrolled students including undergraduates.",
        tooltipSkills: "Research, analytical writing, attention to detail.",
        tooltipMaterials: "State Application (STD 678) plus materials specified per listing.",
        active: false,
      },
    }),
    prisma.internship.create({
      data: {
        id: "cmm78h11h00147ukmsg4jc225",
        field: "polisci",
        company: "Bay Area Council",
        role: "Summer Associates Program",
        category: "Government & Policy",
        location: "San Francisco",
        description: "\u2705 UNDERGRAD OK (juniors/seniors). Applications opening very soon!",
        url: "https://www.bayareacouncil.org/internship-program/",
        deadline: "Applications open March/April 2026",
        period: "Summer 2026 (immersive program)",
        paid: false,
        availability: "soon",
        undergradEligible: true,
        contact: "Check website when applications open",
        tooltipAbout: "Immersive experience in policy research & analysis, program design, global trade, event management.",
        tooltipCandidate: "Collegiate juniors, seniors, and grad students.",
        tooltipSkills: "Policy research, analytical writing, communication, event planning.",
        tooltipMaterials: "Check website starting March 2026 for application requirements.",
        active: false,
      },
    }),
    prisma.internship.create({
      data: {
        id: "cmm78h11h00157ukmjnx6tvjb",
        field: "polisci",
        company: "Santa Clara County Superior Court",
        role: "Judicial Summer Internship",
        category: "Legal & Law",
        location: "San Jos\u00e9",
        description: "\u2705 UNDERGRAD OK. Structured program under Judicial Officers.",
        url: "https://santaclara.courts.ca.gov/general-information/employment/interns-volunteers",
        deadline: "Check court Employment page",
        period: "Summer 2026 (June\u2013July, 2 months)",
        paid: false,
        availability: "open",
        undergradEligible: true,
        contact: "internship@scscourt.org",
        tooltipAbout: "Work under supervision of Judicial Officers in a structured 2-month program.",
        tooltipCandidate: "College students (including undergraduates) and graduates.",
        tooltipSkills: "Interest in judicial system, attention to detail, professional demeanor.",
        tooltipMaterials: "Check employment page or email internship@scscourt.org.",
        active: false,
      },
    }),
    prisma.internship.create({
      data: {
        id: "cmm78h11i00167ukmr2jmyfca",
        field: "polisci",
        company: "Santa Clara Univ. (Resource List)",
        role: "Bay Area Political Internship Directory",
        category: "Government & Policy",
        location: "Bay Area wide",
        description: "\ud83d\udd11 KEY RESOURCE for cold outreach. Lists congressional offices, DA offices, nonprofits, and more.",
        url: "https://www.scu.edu/cas/political-science/beyond-the-classroom/internships-and-fellowships/internships/",
        deadline: "N/A \u2014 use to cold-email orgs directly",
        period: "Varies by organization",
        paid: false,
        availability: "open",
        undergradEligible: true,
        contact: "Prof. Matt Harrigan \u2014 mharrigan@scu.edu",
        tooltipAbout: "Curated directory listing dozens of Bay Area orgs that take political science interns.",
        tooltipCandidate: "Undergrad political science students.",
        tooltipSkills: "Varies by org. Generally: research, writing, communication.",
        tooltipMaterials: "Contact organizations directly with resume and cover letter.",
        active: false,
      },
    }),
    prisma.internship.create({
      data: {
        id: "cmm78h11i00177ukmzodwjmnu",
        field: "polisci",
        company: "SF District Attorney's Office",
        role: "Summer College Internship",
        category: "Legal & Law",
        location: "San Francisco",
        description: "\u2705 UNDERGRAD OK. EMAIL them to ask: SFDAInternship@sfgov.org",
        url: "https://sfdistrictattorney.org/home/careers/college-internships/",
        deadline: "Summer session not yet posted \u2014 email to ask",
        period: "Summer 2026 (likely June\u2013Aug, TBD)",
        paid: false,
        availability: "check",
        undergradEligible: true,
        contact: "SFDAInternship@sfgov.org",
        tooltipAbout: "Assist prosecutors with case files, trial prep, contacting witnesses, managing subpoenas.",
        tooltipCandidate: "Students or recent grads in criminal justice, political science, pre-law.",
        tooltipSkills: "Writing, organization, reliability. Writing sample (\u226410 pages) required.",
        tooltipMaterials: "Cover letter, resume, writing sample, gov photo ID, transcript.",
        active: false,
      },
    }),
    prisma.internship.create({
      data: {
        id: "cmm78h11j00187ukmgb4qwahk",
        field: "polisci",
        company: "SF Dept. of Police Accountability",
        role: "Fall 2026 Internship",
        category: "Government & Policy",
        location: "San Francisco",
        description: "\u2705 UNDERGRAD OK. Great justice reform experience.",
        url: "https://www.sf.gov/apply-internship-dpas-law-and-justice-reform-internship-program",
        deadline: "Summer 2026 deadline passed. Watch for Fall 2026 cycle.",
        period: "Fall 2026 (TBD \u2014 typically ~4 months)",
        paid: false,
        availability: "soon",
        undergradEligible: true,
        contact: "dpa.recruitment@sfgov.org",
        tooltipAbout: "Assist DPA attorneys in trial prep, sentencing, appeals. Police oversight.",
        tooltipCandidate: "Students interested in law, justice reform, police accountability.",
        tooltipSkills: "Research, writing, interest in criminal justice reform.",
        tooltipMaterials: "Resume/CV, cover letter, DPA application form.",
        active: false,
      },
    }),
    prisma.internship.create({
      data: {
        id: "cmm78h11k00197ukmcq38byjf",
        field: "polisci",
        company: "UC Berkeley Public Service Center",
        role: "Public Service Internship (PSI)",
        category: "Nonprofits & Advocacy",
        location: "Bay Area (various community partners)",
        description: "\u2705 UNDERGRAD OK. Cohort model with leadership development.",
        url: "https://publicservice.berkeley.edu/programs/public-service-internship/",
        deadline: "Watch for 2026-27 applications (~spring)",
        period: "Academic Year 2026-27 (8-10 hrs/week)",
        paid: false,
        availability: "soon",
        undergradEligible: true,
        contact: "UC Berkeley Public Service Center",
        tooltipAbout: "Year-long cohort program connecting students with Bay Area social justice orgs.",
        tooltipCandidate: "UC Berkeley students (primarily), including undergraduates.",
        tooltipSkills: "Leadership, community engagement, policy analysis, organizing.",
        tooltipMaterials: "Application through Public Service Center.",
        active: false,
      },
    }),
    prisma.internship.create({
      data: {
        id: "cmm78h11l001a7ukm41r5n8a9",
        field: "polisci",
        company: "Congressional District Offices",
        role: "Intern (various representatives)",
        category: "Government & Policy",
        location: "Bay Area district offices",
        description: "\u2705 UNDERGRAD OK. Bay Area reps: Ro Khanna, Nancy Pelosi, Eric Swalwell, Lateefah Simon, Kevin Mullin, Zoe Lofgren, Jimmy Panetta.",
        url: "https://www.scu.edu/cas/political-science/beyond-the-classroom/internships-and-fellowships/internships/",
        deadline: "Rolling \u2014 most accept applications year-round",
        period: "Summer 2026 or Fall 2026 (flexible)",
        paid: false,
        availability: "open",
        undergradEligible: true,
        contact: "Find contact info on each rep's official website",
        tooltipAbout: "Work in a congressional district office handling constituent services, policy research, event support.",
        tooltipCandidate: "College students, especially political science majors.",
        tooltipSkills: "Communication, writing, research, professionalism.",
        tooltipMaterials: "Resume, cover letter addressed to the specific office.",
        active: false,
      },
    }),
    prisma.internship.create({
      data: {
        id: "cmm78h11m001b7ukm4dtm2emt",
        field: "polisci",
        company: "Rep. Sam Liccardo (CA-16)",
        role: "Congressional Internship",
        category: "Government & Policy",
        location: "Palo Alto District Office / Washington DC",
        description: "\u2705 UNDERGRAD OK. NEW congressman, former San Jose Mayor. Palo Alto is in his district!",
        url: "https://liccardo.house.gov/services/internships",
        deadline: "March 18, 2026",
        period: "Summer 2026 (TBD)",
        paid: false,
        availability: "open",
        undergradEligible: true,
        contact: "See website when Summer 2026 applications open",
        tooltipAbout: "Work with Silicon Valley's newest congressman. Focus on housing, public safety, innovation, climate.",
        tooltipCandidate: "College students. District residents likely prioritized.",
        tooltipSkills: "Constituent services, policy research, communication.",
        tooltipMaterials: "TBD \u2014 check website starting March 2026",
        active: true,
      },
    }),
    prisma.internship.create({
      data: {
        id: "cmm78h11m001c7ukmpwtvk0lv",
        field: "polisci",
        company: "Rep. Ro Khanna (CA-17)",
        role: "Congressional Internship (PAID)",
        category: "Government & Policy",
        location: "Santa Clara District Office / Washington DC",
        description: "\u2705 UNDERGRAD OK. \ud83d\udcb0 PAID $17.75/hr in DC! District office: $15/hr, 12 hrs/week.",
        url: "https://khanna.house.gov/services/internships",
        deadline: "Applications open for Summer 2026",
        period: "Summer 2026 (flexible)",
        paid: true,
        availability: "open",
        undergradEligible: true,
        contact: "DC: Khanna.Interns@mail.house.gov | District: Khanna.Districtintern@mail.house.gov",
        tooltipAbout: "Work on tech policy, housing, innovation with a leading progressive voice.",
        tooltipCandidate: "College students or recent grads. District ties (CA-17) prioritized.",
        tooltipSkills: "Research, writing, constituent services, professionalism.",
        tooltipMaterials: "Resume, short writing sample (max 4 pages), availability, reference.",
        active: true,
      },
    }),
    prisma.internship.create({
      data: {
        id: "cmm78h11n001d7ukm0470o0t5",
        field: "polisci",
        company: "Rep. Kevin Mullin (CA-15)",
        role: "Congressional Internship",
        category: "Government & Policy",
        location: "San Mateo District Office / Washington DC",
        description: "\u2705 UNDERGRAD OK. DC office offers PAID stipend.",
        url: "https://kevinmullin.house.gov/services/internships/",
        deadline: "March 30, 2026",
        period: "Summer 2026 (~4 months, 3 days/week)",
        paid: true,
        availability: "open",
        undergradEligible: true,
        contact: "Check website when applications reopen",
        tooltipAbout: "Serves San Mateo County. Focus on housing, climate, transportation.",
        tooltipCandidate: "College students. Flexible schedule to accommodate classes.",
        tooltipSkills: "Constituent services, research, communication.",
        tooltipMaterials: "TBD when applications reopen",
        active: true,
      },
    }),
    prisma.internship.create({
      data: {
        id: "cmm78h11n001e7ukmqlyzk02t",
        field: "polisci",
        company: "Assemblymember Marc Berman (AD-23)",
        role: "District Office Internship",
        category: "Government & Policy",
        location: "Palo Alto (721 Colorado Ave, Suite 101)",
        description: "\u2705 UNDERGRAD OK. LOCAL! Palo Alto district office. Must reside in AD-23.",
        url: "https://a23.asmdc.org/district-office-internships",
        deadline: "Spring deadline passed. Watch for summer.",
        period: "Varies by term",
        paid: false,
        availability: "check",
        undergradEligible: true,
        contact: "Ruby.Mayne@asm.ca.gov | (650) 324-0224",
        tooltipAbout: "State Assembly work on California policy. Constituent services, policy research.",
        tooltipCandidate: "Must reside in 23rd Assembly District (includes Palo Alto).",
        tooltipSkills: "Research, writing, constituent engagement.",
        tooltipMaterials: "Cover letter, resume, writing sample.",
        active: false,
      },
    }),
    prisma.internship.create({
      data: {
        id: "cmm78h11o001f7ukmiz4rj3i1",
        field: "polisci",
        company: "Eric Swalwell for Governor Campaign",
        role: "Campaign Volunteer/Intern",
        category: "Campaign & Political Orgs",
        location: "East Bay / Statewide",
        description: "\u2705 UNDERGRAD OK. GUBERNATORIAL CAMPAIGN! Polling at 14% (tied for 2nd).",
        url: "https://www.ericswalwell.com/",
        deadline: "Primary: June 2, 2026",
        period: "Through June 2026 primary (ongoing)",
        paid: false,
        availability: "open",
        undergradEligible: true,
        contact: "Campaign website contact form",
        tooltipAbout: "Experience statewide gubernatorial campaign. Phone banking, canvassing, event organizing.",
        tooltipCandidate: "Students interested in electoral politics, campaigns, organizing.",
        tooltipSkills: "Organizing, communication, phone banking, canvassing.",
        tooltipMaterials: "Contact through campaign website volunteer form",
        active: true,
      },
    }),
    prisma.internship.create({
      data: {
        id: "cmm78h11p001g7ukmre9cmr2p",
        field: "polisci",
        company: "Antonio Villaraigosa for Governor Campaign",
        role: "Campaign Volunteer/Intern",
        category: "Campaign & Political Orgs",
        location: "Statewide",
        description: "\u2705 UNDERGRAD OK. Former LA Mayor, former Assembly Speaker.",
        url: "https://www.antonio2026.com/get-involved",
        deadline: "Primary: June 2, 2026",
        period: "Through June 2026 primary",
        paid: false,
        availability: "check",
        undergradEligible: true,
        contact: "Campaign website",
        tooltipAbout: "Work with experienced political operation. Former LA Mayor.",
        tooltipCandidate: "Students interested in campaigns and centrist Democratic politics.",
        tooltipSkills: "Organizing, outreach, data, communication.",
        tooltipMaterials: "Contact through campaign website",
        active: true,
      },
    }),
    prisma.internship.create({
      data: {
        id: "cmm78h11p001h7ukmekosvbws",
        field: "polisci",
        company: "Matt Mahan for Governor Campaign",
        role: "Campaign Volunteer/Intern",
        category: "Campaign & Political Orgs",
        location: "San Jos\u00e9 / Bay Area",
        description: "\u2705 UNDERGRAD OK. Current San Jose Mayor. Silicon Valley moderate. LOCAL!",
        url: "https://mahanforcalifornia.com/volunteer/",
        deadline: "Primary: June 2, 2026",
        period: "Through June 2026 primary",
        paid: false,
        availability: "open",
        undergradEligible: true,
        contact: "Campaign website",
        tooltipAbout: "Newest gubernatorial campaign. Tech-savvy moderate Democrat.",
        tooltipCandidate: "Students interested in moderate Democratic politics, tech policy.",
        tooltipSkills: "Tech-savvy organizing, digital outreach, data.",
        tooltipMaterials: "Contact through campaign website",
        active: true,
      },
    }),
    prisma.internship.create({
      data: {
        id: "cmm78h11q001i7ukm5wrqan3l",
        field: "polisci",
        company: "Stanford Political Science Dept",
        role: "Summer Research College (SRC)",
        category: "Research & Think Tanks",
        location: "Stanford Campus",
        description: "\u2705 UNDERGRAD OK. \ud83d\udcb0 PAID $8,500 stipend! On-campus research with Stanford faculty.",
        url: "https://politicalscience.stanford.edu/undergraduate-program/summer-research-college",
        deadline: "Rolling basis, no later than Friday, Feb 13, 2026 at 5pm",
        period: "June 22 - August 28, 2026 (10 weeks)",
        paid: true,
        availability: "open",
        undergradEligible: true,
        contact: "Margaux Leivenberg (see website)",
        tooltipAbout: "10-week paid research assistantship working directly with Stanford Political Science faculty.",
        tooltipCandidate: "Stanford undergrads only. Must be available 40 hrs/week.",
        tooltipSkills: "Research skills, interest in academic research.",
        tooltipMaterials: "Cover letter for each project, resume, unofficial transcript.",
        active: true,
      },
    }),
    prisma.internship.create({
      data: {
        id: "cmm78h11r001j7ukmyi3qucw6",
        field: "polisci",
        company: "Stanford Public Policy Program",
        role: "Policy Internships & Fellowships",
        category: "Research & Think Tanks",
        location: "Various (DC, Bay Area, international)",
        description: "\u2705 UNDERGRAD OK (must be declared major). Multiple programs.",
        url: "https://publicpolicy.stanford.edu/beyond-classroom/internships-career-resources",
        deadline: "Varies by opportunity",
        period: "Summer 2026 / Academic Year",
        paid: false,
        availability: "check",
        undergradEligible: true,
        contact: "Public Policy Program advising",
        tooltipAbout: "Various internship/fellowship opportunities for public policy students.",
        tooltipCandidate: "Declared public policy or economics majors.",
        tooltipSkills: "Policy analysis, research, writing.",
        tooltipMaterials: "Varies by program \u2014 see website.",
        active: false,
      },
    }),
    prisma.internship.create({
      data: {
        id: "cmm78h11s001k7ukms3a7ezib",
        field: "polisci",
        company: "Stanford Freeman Spogli Institute",
        role: "Global Policy Internships",
        category: "Research & Think Tanks",
        location: "International / Bay Area",
        description: "\u2705 UNDERGRAD OK. Up to $9,000 research funding!",
        url: "https://solo.stanford.edu/",
        deadline: "Varies by program",
        period: "Summer 2026",
        paid: true,
        availability: "check",
        undergradEligible: true,
        contact: "FSI advising",
        tooltipAbout: "International policy internships and research funding.",
        tooltipCandidate: "Stanford students interested in international policy.",
        tooltipSkills: "Policy research, international affairs, languages.",
        tooltipMaterials: "See FSI website and SOLO portal",
        active: true,
      },
    }),
    prisma.internship.create({
      data: {
        id: "cmm78h11s001l7ukmudd09w1z",
        field: "polisci",
        company: "San Jose Mayor Matt Mahan",
        role: "Mayor's Office Internship",
        category: "Government & Policy",
        location: "San Jos\u00e9",
        description: "\u2705 UNDERGRAD OK. LOCAL! Work directly with San Jose Mayor.",
        url: "https://www.sjmayormatt.com/internships",
        deadline: "Check website for current cycle",
        period: "Varies by term",
        paid: false,
        availability: "check",
        undergradEligible: true,
        contact: "See website for application details",
        tooltipAbout: "Work directly in the Mayor's Office on issues affecting Silicon Valley's largest city.",
        tooltipCandidate: "Undergraduate students interested in local government.",
        tooltipSkills: "Policy research, constituent services, project management.",
        tooltipMaterials: "Check website for current application requirements",
        active: true,
      },
    }),
    prisma.internship.create({
      data: {
        id: "cmm78h11t001m7ukmlidy4zv3",
        field: "polisci",
        company: "Santa Clara County District Attorney",
        role: "College Internship Program",
        category: "Legal & Law",
        location: "San Jos\u00e9",
        description: "\u2705 UNDERGRAD OK. County-level prosecution experience.",
        url: "https://countyda.sccgov.org/college-internship-program",
        deadline: "Check website \u2014 typically rolling",
        period: "Varies by term",
        paid: false,
        availability: "check",
        undergradEligible: true,
        contact: "See website for application process",
        tooltipAbout: "Assist prosecutors with criminal cases, legal research, trial preparation.",
        tooltipCandidate: "Undergraduate students interested in criminal justice, pre-law.",
        tooltipSkills: "Legal research, writing, attention to detail.",
        tooltipMaterials: "Application form, resume, cover letter. Background check required.",
        active: true,
      },
    }),
    prisma.internship.create({
      data: {
        id: "cmm78h11u001n7ukmc5fr2rsk",
        field: "polisci",
        company: "Santa Clara County Public Defender",
        role: "Volunteer/Internship Program",
        category: "Legal & Law",
        location: "San Jos\u00e9",
        description: "\u2705 UNDERGRAD OK. Public defense perspective.",
        url: "https://pdo.santaclaracounty.gov/working-public-defenders-office/volunteer-and-job-opportunities",
        deadline: "Rolling applications accepted",
        period: "Flexible",
        paid: false,
        availability: "open",
        undergradEligible: true,
        contact: "See website for volunteer coordinator contact",
        tooltipAbout: "Work with public defenders representing clients who cannot afford private attorneys.",
        tooltipCandidate: "Undergraduate students interested in criminal justice, civil rights.",
        tooltipSkills: "Research, client interaction, legal writing.",
        tooltipMaterials: "See website for current volunteer application process",
        active: true,
      },
    }),
    prisma.internship.create({
      data: {
        id: "cmm78h11u001o7ukm4csf6bpu",
        field: "polisci",
        company: "Silicon Valley Leadership Group",
        role: "Internship Program",
        category: "Government & Policy",
        location: "San Jos\u00e9",
        description: "\u2705 UNDERGRAD OK. Business + policy intersection.",
        url: "https://svlg.org/about-us/internships/",
        deadline: "Check website for current openings",
        period: "Varies",
        paid: false,
        availability: "check",
        undergradEligible: true,
        contact: "See website for application",
        tooltipAbout: "Regional business organization working on policy affecting Silicon Valley.",
        tooltipCandidate: "Students interested in business-government relations.",
        tooltipSkills: "Policy research, business communication, event coordination.",
        tooltipMaterials: "Resume and cover letter \u2014 see website for details",
        active: true,
      },
    }),
    prisma.internship.create({
      data: {
        id: "cmm78h11v001p7ukm3j523u6u",
        field: "polisci",
        company: "Senator Josh Becker (SD-13)",
        role: "State Senate Internship",
        category: "Government & Policy",
        location: "Menlo Park / Sacramento",
        description: "\u2705 UNDERGRAD OK. VERY LOCAL \u2014 Menlo Park office!",
        url: "https://sd13.senate.ca.gov/",
        deadline: "Check website for current term",
        period: "Varies by session",
        paid: false,
        availability: "check",
        undergradEligible: true,
        contact: "Contact district office",
        tooltipAbout: "Work with State Senator representing San Mateo County.",
        tooltipCandidate: "Students interested in state government, environmental issues.",
        tooltipSkills: "Legislative research, constituent services, policy analysis.",
        tooltipMaterials: "Contact office for internship application process",
        active: true,
      },
    }),
    prisma.internship.create({
      data: {
        id: "cmm78h11w001q7ukme3kpzs8r",
        field: "polisci",
        company: "Assemblymember Diane Papen (AD-21)",
        role: "District Office Internship",
        category: "Government & Policy",
        location: "San Mateo",
        description: "\u2705 UNDERGRAD OK. Nearby \u2014 San Mateo County Assembly district. State-level policy work close to home.",
        url: "https://a21.asmdc.org/internship-program",
        deadline: "Check website for term deadlines",
        period: "Varies by term",
        paid: false,
        availability: "check",
        undergradEligible: true,
        contact: "See website for application",
        tooltipAbout: "California State Assembly work on San Mateo County issues. Constituent services, policy research, community engagement.",
        tooltipCandidate: "Students interested in state government, California policy. Interest in Peninsula issues.",
        tooltipSkills: "Research, writing, constituent engagement. Communication and organizational skills.",
        tooltipMaterials: "See website for current application requirements",
        active: true,
      },
    }),
    prisma.internship.create({
      data: {
        id: "cmm78h11w001r7ukmf97b0w1n",
        field: "polisci",
        company: "Representative Jimmy Panetta (CA-19)",
        role: "Congressional Internship",
        category: "Government & Policy",
        location: "Santa Cruz / Salinas / Washington DC",
        description: "\u2705 UNDERGRAD OK. Son of Leon Panetta (former CIA Director, Defense Secretary). Agricultural & coastal policy focus.",
        url: "https://panetta.house.gov/services/internships",
        deadline: "Check website for term deadlines",
        period: "Summer/Fall/Spring terms",
        paid: false,
        availability: "check",
        undergradEligible: true,
        contact: "See website for internship application",
        tooltipAbout: "Work with Congressman representing California's Central Coast. Focus on agriculture, defense, environment, and veterans issues.",
        tooltipCandidate: "College students interested in federal policy, constituent services, congressional operations.",
        tooltipSkills: "Research, writing, constituent communication. Interest in agricultural and coastal policy.",
        tooltipMaterials: "See website for application requirements per term",
        active: true,
      },
    }),
    prisma.internship.create({
      data: {
        id: "cmm78h11x001s7ukmjs1jowbh",
        field: "polisci",
        company: "Representative Lateefah Simon (CA-12)",
        role: "Congressional Internship",
        category: "Government & Policy",
        location: "Oakland / Washington DC",
        description: "\u2705 UNDERGRAD OK. NEW congresswoman (2025). Former BART Board Director, civil rights leader, MacArthur 'Genius' Grant winner.",
        url: "https://simon.house.gov/services/internships",
        deadline: "Check website for current cycle",
        period: "Summer/Fall/Spring terms",
        paid: false,
        availability: "check",
        undergradEligible: true,
        contact: "See website for internship details",
        tooltipAbout: "Work with first-term Congresswoman focused on criminal justice reform, civil rights, and economic justice. Represents Oakland and parts of Contra Costa County.",
        tooltipCandidate: "Students interested in criminal justice reform, civil rights, social justice, progressive politics.",
        tooltipSkills: "Policy research, constituent services, community engagement. Passion for social justice.",
        tooltipMaterials: "Check website for application process",
        active: true,
      },
    }),
    prisma.internship.create({
      data: {
        id: "cmm78h11y001t7ukmmyawfgmm",
        field: "polisci",
        company: "Assemblymember Patrick Ahrens (AD-26)",
        role: "District Office Internship",
        category: "Government & Policy",
        location: "Cupertino",
        description: "\u2705 UNDERGRAD OK. VERY LOCAL \u2014 Cupertino! (5 miles from Palo Alto). State Assembly work close to Stanford/home.",
        url: "https://a26.asmdc.org/assembly-district-26-internships",
        deadline: "April 12, 2026",
        period: "Varies by term",
        paid: false,
        availability: "open",
        undergradEligible: true,
        contact: "See website for application",
        tooltipAbout: "California State Assembly representing Cupertino, Sunnyvale, Santa Clara. Work on state policy affecting Silicon Valley.",
        tooltipCandidate: "Students interested in state government, California policy, tech regulation, local issues.",
        tooltipSkills: "Legislative research, constituent services, policy analysis. Communication skills.",
        tooltipMaterials: "Check website for current application requirements",
        active: true,
      },
    }),
    prisma.internship.create({
      data: {
        id: "cmm78h11y001u7ukm09cxjdfa",
        field: "polisci",
        company: "Assemblymember Ash Kalra (AD-25)",
        role: "Assembly Internship",
        category: "Government & Policy",
        location: "San Jos\u00e9",
        description: "\u2705 UNDERGRAD OK. San Jose Assembly member. Progressive voice on criminal justice reform, workers' rights, housing.",
        url: "https://a25.asmdc.org/assembly-internship-opportunities",
        deadline: "Check website for term deadlines",
        period: "Varies by term",
        paid: false,
        availability: "check",
        undergradEligible: true,
        contact: "See website for application",
        tooltipAbout: "State Assembly work with progressive leader. Focus on criminal justice reform, workers' rights, affordable housing.",
        tooltipCandidate: "Students interested in progressive state policy, criminal justice reform, labor issues.",
        tooltipSkills: "Policy research, legislative analysis, constituent engagement. Progressive values.",
        tooltipMaterials: "See website for application process",
        active: true,
      },
    }),
    prisma.internship.create({
      data: {
        id: "cmm78h11z001v7ukm75d8fpyq",
        field: "polisci",
        company: "Assemblymember Alex Lee (AD-24)",
        role: "Internship Program",
        category: "Government & Policy",
        location: "Milpitas",
        description: "\u2705 UNDERGRAD OK. Youngest CA legislator when elected (age 25). Progressive champion. Represents Milpitas/Fremont area.",
        url: "https://a24.asmdc.org/internship-program",
        deadline: "Check website for term deadlines",
        period: "Varies by term",
        paid: false,
        availability: "check",
        undergradEligible: true,
        contact: "See website for details",
        tooltipAbout: "Work with young progressive leader (first Gen Z state legislator in US). Focus on housing, climate, workers' rights.",
        tooltipCandidate: "Students interested in progressive politics, youth in government, climate action, housing policy.",
        tooltipSkills: "Social media savvy, policy research, grassroots organizing. Progressive values.",
        tooltipMaterials: "Check website for application requirements",
        active: true,
      },
    }),
    prisma.internship.create({
      data: {
        id: "cmm78h11z001w7ukmwf8smyru",
        field: "polisci",
        company: "Senator Dave Cortese (SD-15)",
        role: "State Senate Internship",
        category: "Government & Policy",
        location: "San Jos\u00e9 / Sacramento",
        description: "\u2705 UNDERGRAD OK. Represents Santa Clara County in State Senate. Former County Supervisor and San Jose Councilmember.",
        url: "https://sd15.senate.ca.gov/",
        deadline: "Contact office for deadlines",
        period: "Varies by session",
        paid: false,
        availability: "check",
        undergradEligible: true,
        contact: "Contact district office",
        tooltipAbout: "State Senate work representing Santa Clara County. Focus on healthcare, education, environmental protection.",
        tooltipCandidate: "Students interested in state government, healthcare policy, environmental issues.",
        tooltipSkills: "Legislative research, policy analysis, constituent services. Interest in state-level policy.",
        tooltipMaterials: "Contact office for internship information",
        active: false,
      },
    }),
    prisma.internship.create({
      data: {
        id: "cmm78h120001x7ukmb2hc9nuu",
        field: "polisci",
        company: "Senator Scott Wiener (SD-11)",
        role: "State Senate Internship",
        category: "Government & Policy",
        location: "San Francisco / Sacramento",
        description: "\u2705 UNDERGRAD OK. LGBTQ+ rights champion. Progressive leader on housing, transit, drug policy reform. SF-based.",
        url: "https://sd11.senate.ca.gov/internship",
        deadline: "Check website for term deadlines",
        period: "Varies by session",
        paid: false,
        availability: "check",
        undergradEligible: true,
        contact: "See internship page",
        tooltipAbout: "Work with prominent progressive state senator. Leading voice on housing (YIMBY), LGBTQ+ rights, drug policy reform, transit.",
        tooltipCandidate: "Students interested in progressive state policy, LGBTQ+ rights, housing, transit, criminal justice reform.",
        tooltipSkills: "Policy research, constituent services, comfort with progressive advocacy on controversial issues.",
        tooltipMaterials: "See website for application process",
        active: true,
      },
    }),
    prisma.internship.create({
      data: {
        id: "cmm78h121001y7ukmqx2ye8nf",
        field: "polisci",
        company: "Silicon Valley Council of Nonprofits",
        role: "Nonprofit Sector Internship",
        category: "Nonprofits & Advocacy",
        location: "San Jos\u00e9 area",
        description: "\u2705 UNDERGRAD OK. Umbrella organization connecting nonprofits. Job board lists opportunities across many organizations.",
        url: "https://www.svcn.org/job-board-pages/view-jobs",
        deadline: "Check job board for postings",
        period: "Varies",
        paid: false,
        availability: "check",
        undergradEligible: true,
        contact: "See job board",
        tooltipAbout: "Resource hub for Silicon Valley nonprofits. Job board aggregates opportunities from many member organizations.",
        tooltipCandidate: "Students interested in nonprofit sector, community development, social services.",
        tooltipSkills: "Varies by posting. Generally: communication, project management, passion for nonprofit work.",
        tooltipMaterials: "Varies by organization \u2014 check individual postings",
        active: false,
      },
    }),
    prisma.internship.create({
      data: {
        id: "cmm78h121001z7ukmgicon70i",
        field: "polisci",
        company: "ACLU of Northern California",
        role: "Internship Program",
        category: "Nonprofits & Advocacy",
        location: "San Francisco",
        description: "\u2705 UNDERGRAD OK. Premier civil liberties organization.",
        url: "https://www.aclu.org/careers/internships/",
        deadline: "Check for current openings",
        period: "Summer/Academic year",
        paid: false,
        availability: "check",
        undergradEligible: true,
        contact: "See ACLU careers page",
        tooltipAbout: "Work on civil liberties litigation, advocacy, and policy.",
        tooltipCandidate: "Students passionate about constitutional rights.",
        tooltipSkills: "Legal research, policy analysis, advocacy, writing.",
        tooltipMaterials: "Resume, cover letter, writing sample.",
        active: false,
      },
    }),
    prisma.internship.create({
      data: {
        id: "cmm78h12200207ukm34pjgo2h",
        field: "polisci",
        company: "Asian Law Alliance",
        role: "Internship/Volunteer",
        category: "Nonprofits & Advocacy",
        location: "San Jos\u00e9",
        description: "\u2705 UNDERGRAD OK. LOCAL \u2014 San Jose! Immigration, housing, employment law.",
        url: "https://www.asianlawalliance.org/get-involved",
        deadline: "Rolling applications",
        period: "Flexible",
        paid: false,
        availability: "open",
        undergradEligible: true,
        contact: "See website for volunteer/intern info",
        tooltipAbout: "Community-based legal services for Asian Americans and Pacific Islanders.",
        tooltipCandidate: "Students interested in public interest law, immigrant rights.",
        tooltipSkills: "Legal research, client interaction, bilingual abilities helpful.",
        tooltipMaterials: "Contact organization for volunteer/internship application",
        active: false,
      },
    }),
    prisma.internship.create({
      data: {
        id: "cmm78h12300217ukmsnfb9wyb",
        field: "polisci",
        company: "Rep. Zoe Lofgren (CA-18)",
        role: "Congressional Internship",
        category: "Government & Policy",
        location: "San Jos\u00e9 / Washington DC",
        description: "\u2705 UNDERGRAD OK. 30+ years in Congress! Immigration and tech policy expert.",
        url: "https://lofgren.house.gov/services/internships",
        deadline: "Rolling applications accepted",
        period: "Summer/Fall/Spring terms",
        paid: false,
        availability: "open",
        undergradEligible: true,
        contact: "DC: internships.lofgren@mail.house.gov | District: lofgren.casework@mail.house.gov",
        tooltipAbout: "Work with senior member of Congress. Expert on immigration, tech policy, election law.",
        tooltipCandidate: "Students interested in immigration policy, technology regulation.",
        tooltipSkills: "Research, writing, constituent services.",
        tooltipMaterials: "Resume, cover letter, writing sample.",
        active: true,
      },
    }),
    prisma.internship.create({
      data: {
        id: "cmm78h12400227ukmrnc43n56",
        field: "polisci",
        company: "Bay Area Legal Aid",
        role: "Internship/Volunteer",
        category: "Nonprofits & Advocacy",
        location: "San Jos\u00e9 / Oakland / San Francisco",
        description: "\u2705 UNDERGRAD OK. Free legal services for low-income residents.",
        url: "https://baylegal.org/get-involved/volunteer/",
        deadline: "Rolling applications",
        period: "Flexible",
        paid: false,
        availability: "open",
        undergradEligible: true,
        contact: "See volunteer page",
        tooltipAbout: "Provide free legal services to low-income individuals. Housing, family law, consumer protection.",
        tooltipCandidate: "Students interested in public interest law, social justice.",
        tooltipSkills: "Legal research, client interaction, empathy. Bilingual helpful.",
        tooltipMaterials: "See website for volunteer/internship application",
        active: true,
      },
    }),
    prisma.internship.create({
      data: {
        id: "cmm78h12500237ukmogqv40pa",
        field: "polisci",
        company: "Equal Rights Advocates",
        role: "Undergraduate Internship",
        category: "Nonprofits & Advocacy",
        location: "San Francisco",
        description: "\u2705 UNDERGRAD OK. Gender justice legal advocacy.",
        url: "https://www.equalrights.org/join-our-team/#undergrad-internships",
        deadline: "Check for current cycle",
        period: "Summer/Academic year",
        paid: false,
        availability: "check",
        undergradEligible: true,
        contact: "See website for application",
        tooltipAbout: "Legal advocacy for gender justice. Workplace discrimination, sexual harassment, equal pay.",
        tooltipCandidate: "Undergraduate students interested in gender justice.",
        tooltipSkills: "Legal research, policy analysis, client interaction.",
        tooltipMaterials: "See website for undergraduate internship application requirements",
        active: false,
      },
    }),
    prisma.internship.create({
      data: {
        id: "cmm78h12600247ukm5aia1lnj",
        field: "polisci",
        company: "Alameda County District Attorney",
        role: "Youth Employment Program",
        category: "Legal & Law",
        location: "Oakland",
        description: "\u2705 UNDERGRAD OK. \ud83d\udcb0 PAID youth employment program.",
        url: "https://www.alcoda.org/community-outreach/youth-employment-programs/",
        deadline: "Check for current cycle",
        period: "Summer program",
        paid: true,
        availability: "check",
        undergradEligible: true,
        contact: "See website for program details",
        tooltipAbout: "Paid summer employment program with the Alameda County DA's Office.",
        tooltipCandidate: "Undergraduate students interested in criminal justice.",
        tooltipSkills: "Legal research, office administration, professionalism.",
        tooltipMaterials: "See website for youth employment application process",
        active: false,
      },
    }),
    prisma.internship.create({
      data: {
        id: "e9efde18c192d10067e6d12c",
        field: "polisci",
        company: "City of Palo Alto",
        role: "Public Works Dept Intern (Various Positions)",
        category: "Government",
        location: "Palo Alto, CA",
        description: "The City of Palo Alto is recruiting 12 paid interns for its 2026 Summer Internship Program. Positions span multiple departments including watershed protection, sustainability, zero waste, and water quality control. Interns contribute to active projects in stormwater/pollution prevention, sustainability/climate action, waste reduction, and water quality control.",
        url: "https://www.governmentjobs.com/jobs/5250758-0/public-works-dept-intern-various-positions",
        deadline: "March 24, 2026",
        period: "Summer 2026",
        paid: true,
        availability: "open",
        undergradEligible: true,
        contact: null,
        tooltipAbout: null,
        tooltipCandidate: null,
        tooltipSkills: null,
        tooltipMaterials: null,
        active: true,
      },
    }),
    prisma.internship.create({
      data: {
        id: "d9ad61c93cf3e3dfd938d9ad",
        field: "polisci",
        company: "City of Palo Alto",
        role: "Summer Intern (Various Positions City Wide)",
        category: "Government & Policy",
        location: "Palo Alto, CA",
        description: "20 paid internship opportunities across multiple city departments including City Manager's Office, Library Services, Office of Transportation, Parks & Golf, and Planning & Development Services. Structured cohort program with orientation, leadership workshops, networking events, industry panels, site visits, and closing ceremony.",
        url: "https://www.governmentjobs.com/jobs/5248901-0/summer-intern-various-positions-city-wide",
        deadline: "March 20, 2026",
        period: "Summer 2026",
        paid: true,
        availability: "open",
        undergradEligible: true,
        contact: null,
        tooltipAbout: null,
        tooltipCandidate: null,
        tooltipSkills: null,
        tooltipMaterials: null,
        active: true,
      },
    }),
    prisma.internship.create({
      data: {
        id: "3d102bcec3e7cc7ba4d4b8db",
        field: "polisci",
        company: "County of Santa Clara",
        role: "Student Intern, Level III",
        category: "Government & Policy",
        location: "Santa Clara County, CA",
        description: "Intern under close supervision gaining practical experience in policy and operations. Responsibilities include learning agency policies and procedures, collecting and tabulating data, interpreting findings, and participating in team analysis and report preparation. Requires 2.5+ GPA and current enrollment or recent graduation.",
        url: "https://www.governmentjobs.com/jobs/5184895-0/student-intern-level-iii",
        deadline: "December 31, 2026",
        period: null,
        paid: true,
        availability: "open",
        undergradEligible: true,
        contact: null,
        tooltipAbout: null,
        tooltipCandidate: null,
        tooltipSkills: null,
        tooltipMaterials: null,
        active: false,
      },
    }),
    prisma.internship.create({
      data: {
        id: "3855fef689a31bd58f2b92cb",
        field: "polisci",
        company: "Santa Clara County Superior Court",
        role: "Judicial Intern / Self-Help Center Intern",
        category: "Legal & Law",
        location: "Santa Clara County, CA",
        description: "Undergrads and law students can intern at the Self-Help Center or as Judicial Interns. Work with the public on family law matters, assist judges, and gain hands-on court experience. Minimum 2-month commitment, at least 16 hours/week.",
        url: "https://santaclara.courts.ca.gov/general-information/employment/interns-volunteers",
        deadline: null,
        period: null,
        paid: false,
        availability: "open",
        undergradEligible: true,
        contact: "good to gain experience in law",
        tooltipAbout: null,
        tooltipCandidate: null,
        tooltipSkills: null,
        tooltipMaterials: null,
        active: false,
      },
    }),
  ]);

  // Create tracking data
  await Promise.all([
    prisma.userInternship.create({
      data: {
        userId: "cmm78nsh3000224km4qldj77d",
        internshipId: "cmm78h11m001c7ukmpwtvk0lv",
        status: "Applied",
        priority: 3,
        notes: null,
      },
    }),
    prisma.userInternship.create({
      data: {
        userId: "cmm78nsh3000224km4qldj77d",
        internshipId: "e9efde18c192d10067e6d12c",
        status: "Researching",
        priority: 3,
        notes: null,
      },
    }),
    prisma.userInternship.create({
      data: {
        userId: "cmm78nsh3000224km4qldj77d",
        internshipId: "d9ad61c93cf3e3dfd938d9ad",
        status: "Researching",
        priority: 3,
        notes: null,
      },
    }),
    prisma.userInternship.create({
      data: {
        userId: "cmm78nsh3000224km4qldj77d",
        internshipId: "3d102bcec3e7cc7ba4d4b8db",
        status: "Researching",
        priority: 3,
        notes: null,
      },
    }),
    prisma.userInternship.create({
      data: {
        userId: "cmm78nsh3000224km4qldj77d",
        internshipId: "cmm78h11h00157ukmjnx6tvjb",
        status: "Researching",
        priority: 3,
        notes: null,
      },
    }),
    prisma.userInternship.create({
      data: {
        userId: "cmm78nsh3000224km4qldj77d",
        internshipId: "cmm78h11m001b7ukm4dtm2emt",
        status: "Researching",
        priority: 3,
        notes: null,
      },
    }),
    prisma.userInternship.create({
      data: {
        userId: "cmm78nsh3000224km4qldj77d",
        internshipId: "cmm78h12400227ukmrnc43n56",
        status: "Researching",
        priority: 3,
        notes: null,
      },
    }),
    prisma.userInternship.create({
      data: {
        userId: "cmm78nsh3000224km4qldj77d",
        internshipId: "cmm78h12300217ukmsnfb9wyb",
        status: "Researching",
        priority: 3,
        notes: null,
      },
    }),
    prisma.userInternship.create({
      data: {
        userId: "cmm78nsh3000224km4qldj77d",
        internshipId: "cmm78h120001x7ukmb2hc9nuu",
        status: "Researching",
        priority: 2,
        notes: null,
      },
    }),
    prisma.userInternship.create({
      data: {
        userId: "cmm78nsh3000224km4qldj77d",
        internshipId: "cmm78h11z001v7ukm75d8fpyq",
        status: "Researching",
        priority: 3,
        notes: null,
      },
    }),
    prisma.userInternship.create({
      data: {
        userId: "cmm78nsh3000224km4qldj77d",
        internshipId: "cmm78h11y001t7ukmmyawfgmm",
        status: "Researching",
        priority: 3,
        notes: null,
      },
    }),
    prisma.userInternship.create({
      data: {
        userId: "cmm78nsh3000224km4qldj77d",
        internshipId: "cmm78h11n001d7ukm0470o0t5",
        status: "Researching",
        priority: 3,
        notes: null,
      },
    }),
    prisma.userInternship.create({
      data: {
        userId: "cmm78nsh3000224km4qldj77d",
        internshipId: "cmm78h11o001f7ukmiz4rj3i1",
        status: "Not Started",
        priority: 2,
        notes: null,
      },
    }),
    prisma.userInternship.create({
      data: {
        userId: "cmm78nsh3000224km4qldj77d",
        internshipId: "cmm78h11p001g7ukmre9cmr2p",
        status: "Not Started",
        priority: 2,
        notes: null,
      },
    }),
    prisma.userInternship.create({
      data: {
        userId: "cmm78nsh3000224km4qldj77d",
        internshipId: "cmm78h11p001h7ukmekosvbws",
        status: "Researching",
        priority: 3,
        notes: null,
      },
    }),
  ]);

  console.log("Seeded successfully!");
  console.log(`  Users: 2`);
  console.log(`  Internships: 76`);
  console.log(`  Tracking records: 16`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
